"use client";
import { useCallback, useEffect, useState } from "react";
import RentalRecordBrowser from "./RentalRecordBrowser";
const requestStates=["submitted","reviewing","scheduled","in_progress","completed","cancelled"],workStates=["assigned","scheduled","in_progress","completed","cancelled"];
const dollars=(value)=>value==null?"—":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(value/100),toCents=(value)=>value===""?null:Math.round(Number(value)*100),label=(value)=>value?.replaceAll("_"," ")||"—";
const empty={maintenanceRequests:[],contractors:[],workOrders:[],workEvents:[]};
export default function RentalMaintenancePanel({initialData=null}){
 const[data,setData]=useState(initialData||empty),[selectedId,setSelectedId]=useState(""),[showContractor,setShowContractor]=useState(false),[showWorkOrder,setShowWorkOrder]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const load=useCallback(()=>fetch("/api/rental").then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error);setData(body);}),[]);useEffect(()=>{if(!initialData)load().catch(reason=>setError(reason.message));},[initialData,load]);
 const activeId=data.maintenanceRequests.some(item=>item.id===selectedId)?selectedId:data.maintenanceRequests[0]?.id||"",selected=data.maintenanceRequests.find(item=>item.id===activeId);
 async function post(payload,text){setError("");setMessage("");try{const response=await fetch("/api/rental",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),body=await response.json();if(!response.ok)throw new Error(body.error);await load();setMessage(text);return true;}catch(reason){setError(reason.message);return false;}}
 const values=(form)=>Object.fromEntries(new FormData(form));
 async function saveContractor(event){event.preventDefault();const value=values(event.currentTarget),saved=await post({operation:"save-contractor",contractor:{businessName:value.businessName,contactName:value.contactName,email:value.email,phone:value.phone,trade:value.trade,licenseReference:value.licenseReference,insuranceExpiration:value.insuranceExpiration,w9Status:value.w9Status,taxClassification:value.taxClassification,taxIdLast4:value.taxIdLast4}},"Contractor saved.");if(saved)setShowContractor(false);}
 async function updateRequest(event,id){event.preventDefault();const value=values(event.currentTarget);await post({operation:"update-maintenance-request",requestId:id,status:value.status,ownerNotes:value.ownerNotes},"Request updated.");}
 async function createWorkOrder(event,requestId){event.preventDefault();const value=values(event.currentTarget),saved=await post({operation:"create-maintenance-work-order",workOrder:{requestId,contractorId:value.contractorId,scopeOfWork:value.scopeOfWork,scheduledStart:value.scheduledStart,scheduledEnd:value.scheduledEnd,entryInstructions:value.entryInstructions,estimatedCostCents:toCents(value.estimatedCost),publicNote:value.publicNote,privateNote:value.privateNote}},"Work order created.");if(saved)setShowWorkOrder(false);}
 async function updateWorkOrder(event,id){event.preventDefault();const value=values(event.currentTarget);await post({operation:"update-maintenance-work-order",workOrder:{id,status:value.status,scheduledStart:value.scheduledStart,scheduledEnd:value.scheduledEnd,estimatedCostCents:toCents(value.estimatedCost),actualCostCents:toCents(value.actualCost),invoiceReference:value.invoiceReference,invoiceDocumentId:value.invoiceDocumentId,completionDocumentId:value.completionDocumentId,publicNote:value.publicNote,privateNote:value.privateNote}},"Work order updated.");}
 return <section className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-widest text-amber-700">Maintenance operations</p><h2 className="mt-2 text-2xl font-black">Requests and work orders</h2><p className="mt-2 text-slate-600">Select a request to coordinate status, assignment, evidence, notes, and work history.</p></div><button type="button" onClick={()=>setShowContractor(value=>!value)} className="rounded-xl border px-4 py-2 font-bold">{showContractor?"Cancel contractor setup":"Contractor directory"}</button></div>
 {error?<p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-red-800">{error}</p>:null}{message?<p role="status" className="mt-4 rounded-xl bg-emerald-50 p-3 text-emerald-800">{message}</p>:null}
 {showContractor?<section className="mt-6 rounded-2xl border bg-slate-50 p-5"><h3 className="text-lg font-black">Contractor directory</h3><p className="mt-1 text-sm text-slate-600">W-9 and tax details remain owner-only.</p><div className="mt-3 flex flex-wrap gap-2">{data.contractors.map(item=><span key={item.id} className="rounded-full bg-white px-3 py-2 text-sm"><strong>{item.business_name}</strong> · {item.trade||"General"} · W-9 {label(item.w9_status)}</span>)}</div><form aria-label="Add contractor" onSubmit={saveContractor} className="mt-5 grid gap-3 md:grid-cols-4"><input required name="businessName" placeholder="Business name" className="rounded-lg border p-3"/><input name="contactName" placeholder="Contact name" className="rounded-lg border p-3"/><input name="trade" placeholder="Trade" className="rounded-lg border p-3"/><input name="phone" placeholder="Phone" className="rounded-lg border p-3"/><input name="email" type="email" placeholder="Email" className="rounded-lg border p-3"/><input name="licenseReference" placeholder="License reference" className="rounded-lg border p-3"/><input name="insuranceExpiration" type="date" className="rounded-lg border p-3"/><select name="w9Status" className="rounded-lg border p-3"><option value="not_requested">W-9 not requested</option><option value="requested">W-9 requested</option><option value="received">W-9 received</option><option value="reviewed">W-9 reviewed</option></select><input name="taxClassification" placeholder="Tax classification" className="rounded-lg border p-3"/><input name="taxIdLast4" maxLength={4} placeholder="Tax ID last 4" className="rounded-lg border p-3"/><button className="rounded-lg bg-slate-950 p-3 font-bold text-white">Save contractor</button></form></section>:null}
 <RentalRecordBrowser title="Maintenance requests" records={data.maintenanceRequests} selectedId={activeId} onSelect={id=>{setSelectedId(id);setShowWorkOrder(false);}} getTitle={item=>item.title} getSubtitle={item=>`${label(item.status)} · ${label(item.priority)} priority`} emptyMessage="No maintenance requests have been submitted.">
  {!selected?<p className="text-sm text-slate-500">Select a maintenance request to review its details.</p>:<RequestDetail request={selected} workOrders={data.workOrders.filter(item=>item.request_id===selected.id)} workEvents={data.workEvents} contractors={data.contractors} showWorkOrder={showWorkOrder} setShowWorkOrder={setShowWorkOrder} updateRequest={updateRequest} createWorkOrder={createWorkOrder} updateWorkOrder={updateWorkOrder}/>}
 </RentalRecordBrowser></section>;
}
function RequestDetail({request,workOrders,workEvents,contractors,showWorkOrder,setShowWorkOrder,updateRequest,createWorkOrder,updateWorkOrder}){return <div><p className="text-xs font-bold uppercase tracking-widest text-slate-500">Selected request</p><h3 className="mt-2 text-xl font-black">{request.title}</h3><p className="mt-2 text-slate-700">{request.description}</p><dl className="mt-4 grid gap-3 sm:grid-cols-3"><Fact term="Status" value={label(request.status)}/><Fact term="Priority" value={label(request.priority)}/><Fact term="Entry permitted" value={request.permission_to_enter?"Yes":"No"}/><Fact term="Submitted" value={request.submitted_at?new Date(request.submitted_at).toLocaleDateString():"—"}/><Fact term="Contact phone" value={request.contact_phone||"—"}/><Fact term="Work orders" value={String(workOrders.length)}/></dl><form onSubmit={event=>updateRequest(event,request.id)} className="mt-5 grid gap-2 md:grid-cols-[180px_1fr_auto]"><select name="status" defaultValue={request.status} className="rounded-lg border p-2">{requestStates.map(state=><option key={state}>{state}</option>)}</select><input name="ownerNotes" defaultValue={request.owner_notes||""} placeholder="Owner notes" className="rounded-lg border p-2"/><button className="rounded-lg bg-slate-950 px-4 font-bold text-white">Save request</button></form><div className="mt-6 flex items-center justify-between border-t pt-5"><h4 className="font-black">Work orders and timeline</h4><button type="button" onClick={()=>setShowWorkOrder(value=>!value)} className="rounded-xl bg-amber-500 px-4 py-2 font-black">{showWorkOrder?"Cancel":"Create work order"}</button></div>{showWorkOrder?<WorkOrderForm requestId={request.id} contractors={contractors} submit={createWorkOrder}/>:null}{workOrders.length===0?<p className="mt-4 text-sm text-slate-500">No work order has been created.</p>:workOrders.map(order=><WorkOrder key={order.id} order={order} events={workEvents.filter(item=>item.work_order_id===order.id)} submit={updateWorkOrder}/>)}</div>}
function WorkOrderForm({requestId,contractors,submit}){return <form aria-label="Create work order" onSubmit={event=>submit(event,requestId)} className="mt-4 grid gap-2 rounded-xl bg-slate-50 p-4 md:grid-cols-3"><select name="contractorId" className="rounded-lg border p-2"><option value="">Unassigned</option>{contractors.filter(item=>item.status==="active").map(item=><option key={item.id} value={item.id}>{item.business_name}</option>)}</select><input required name="scopeOfWork" placeholder="Scope of work" className="rounded-lg border p-2"/><input name="estimatedCost" type="number" min="0" step=".01" placeholder="Estimate" className="rounded-lg border p-2"/><input name="scheduledStart" type="datetime-local" className="rounded-lg border p-2"/><input name="scheduledEnd" type="datetime-local" className="rounded-lg border p-2"/><input name="entryInstructions" placeholder="Entry instructions" className="rounded-lg border p-2"/><input name="publicNote" placeholder="Tenant-visible update" className="rounded-lg border p-2"/><input name="privateNote" placeholder="Private note" className="rounded-lg border p-2"/><button className="rounded-lg bg-slate-950 p-2 font-bold text-white">Create work order</button></form>}
function WorkOrder({order,events,submit}){return <article className="mt-4 rounded-xl border p-4"><strong>{order.scope_of_work}</strong><p className="mt-1 text-sm capitalize">{label(order.status)} · Estimate {dollars(order.estimated_cost_cents)} · Actual {dollars(order.actual_cost_cents)}</p><form onSubmit={event=>submit(event,order.id)} className="mt-3 grid gap-2 md:grid-cols-4"><select name="status" defaultValue={order.status} className="rounded-lg border p-2">{workStates.map(state=><option key={state}>{state}</option>)}</select><input name="scheduledStart" type="datetime-local" className="rounded-lg border p-2"/><input name="scheduledEnd" type="datetime-local" className="rounded-lg border p-2"/><input name="estimatedCost" type="number" min="0" step=".01" placeholder="Estimate" className="rounded-lg border p-2"/><input name="actualCost" type="number" min="0" step=".01" placeholder="Actual cost" className="rounded-lg border p-2"/><input name="invoiceReference" placeholder="Invoice reference" className="rounded-lg border p-2"/><input name="invoiceDocumentId" placeholder="Invoice document ID" className="rounded-lg border p-2"/><input name="completionDocumentId" placeholder="Completion evidence ID" className="rounded-lg border p-2"/><input name="publicNote" placeholder="Tenant-visible update" className="rounded-lg border p-2"/><input name="privateNote" placeholder="Private note" className="rounded-lg border p-2"/><button className="rounded-lg bg-slate-950 p-2 font-bold text-white">Update work order</button></form><div className="mt-3 border-t pt-3"><p className="text-xs font-bold uppercase text-slate-500">Timeline</p>{events.length===0?<p className="mt-2 text-sm text-slate-500">No work events recorded.</p>:events.map(item=><p key={item.id} className="mt-2 text-sm"><strong>{label(item.event_type)}</strong>{item.public_note?` · Tenant: ${item.public_note}`:""}{item.private_note?` · Private: ${item.private_note}`:""}</p>)}</div></article>}
function Fact({term,value}){return <div><dt className="text-xs font-bold uppercase text-slate-500">{term}</dt><dd className="mt-1 font-bold capitalize">{value}</dd></div>}
