"use client";
import { useEffect, useMemo, useState } from "react";
import RentalRecordBrowser from "./RentalRecordBrowser";

const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" });
const label = (value) => value?.replaceAll("_", " ") || "—";
export function buildRentActivity(charges, payments, settlements) {
  const byPayment = new Map(settlements.map((item) => [item.payment_id, item]));
  return [...charges.map((item) => ({ ...item, id: `charge:${item.id}`, sourceId: item.id, kind: "charge" })),
    ...payments.map((item) => ({ ...item, id: `payment:${item.id}`, sourceId: item.id, kind: "payment", settlement: byPayment.get(item.id) || null }))];
}

export default function RentalPaymentsPanel({ initialData = null, initialAccount }) {
  const [account, setAccount] = useState(initialAccount), [data, setData] = useState(initialData || { openCharges: [], payments: [], settlements: [], schedules: [] });
  const [selectedId, setSelectedId] = useState(""), [showOffline, setShowOffline] = useState(false), [showSetup, setShowSetup] = useState(false);
  const [message, setMessage] = useState(""), [saved, setSaved] = useState(""), [busy, setBusy] = useState(false);
  async function loadRentalData() { const response = await fetch("/api/rental"), body = await response.json(); if (!response.ok) throw new Error(body.error || "Unable to load rent collection data."); setData({ openCharges: body.openCharges || [], payments: body.payments || [], settlements: body.settlements || [], schedules: body.schedules || [] }); }
  async function loadAccount() { const response = await fetch("/api/rental/stripe-account"), body = await response.json(); if (!response.ok) throw new Error(body.error); setAccount(body.account); }
  useEffect(() => { if (initialData) return; loadRentalData().catch((error) => setMessage(error.message)); loadAccount().catch((error) => setMessage(error.message)); }, [initialData]);
  const records = useMemo(() => buildRentActivity(data.openCharges, data.payments, data.settlements), [data]);
  const activeId = records.some((item) => item.id === selectedId) ? selectedId : records[0]?.id || "";
  const selected = records.find((item) => item.id === activeId);
  async function connect() { setBusy(true); setMessage(""); try { const response = await fetch("/api/rental/stripe-account", { method: "POST" }), body = await response.json(); if (!response.ok) throw new Error(body.error); window.location.assign(body.url); } catch (error) { setMessage(error.message); setBusy(false); } }
  async function post(body, success) { setBusy(true); setMessage(""); setSaved(""); try { const response = await fetch("/api/rental", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }), result = await response.json(); if (!response.ok) throw new Error(result.error); setSaved(success(result)); await loadRentalData(); return true; } catch (error) { setMessage(error.message); return false; } finally { setBusy(false); } }
  async function recordOffline(event) { event.preventDefault(); const element = event.currentTarget, form = new FormData(element); const success = await post({ operation: "record-offline-payment", payment: { chargeId: form.get("chargeId"), paymentMethod: form.get("paymentMethod"), amountCents: Math.round(Number(form.get("amount")) * 100), receivedAt: new Date(`${form.get("receivedDate")}T12:00:00`).toISOString(), receiptReference: form.get("receiptReference"), notes: form.get("notes") } }, () => "Offline payment recorded and rent balance updated."); if (success) { element.reset(); setShowOffline(false); } }
  const enabled = account?.status === "enabled";
  return <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-widest text-amber-700">Rent collection</p><h2 className="mt-2 text-2xl font-black">Rent &amp; payments</h2><p className="mt-2 text-slate-600">Review charges and payment history, then act on the selected record.</p></div><div className="flex gap-2"><button type="button" onClick={() => setShowOffline((value) => !value)} className="rounded-xl bg-amber-500 px-4 py-2 font-black">{showOffline ? "Cancel offline payment" : "Record offline payment"}</button><button type="button" onClick={() => setShowSetup((value) => !value)} className="rounded-xl border px-4 py-2 font-bold">{showSetup ? "Hide billing setup" : "Billing setup"}</button></div></div>
    {message ? <p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-red-800">{message}</p> : null}{saved ? <p role="status" className="mt-4 rounded-xl bg-emerald-50 p-3 text-emerald-800">{saved}</p> : null}
    {showOffline ? <form aria-label="Record offline payment" onSubmit={recordOffline} className="mt-6 grid gap-4 rounded-2xl border border-amber-200 bg-amber-50 p-5 md:grid-cols-2"><label className="text-sm font-bold md:col-span-2">Open rent charge<select name="chargeId" required className="mt-1 w-full rounded-xl border p-3 font-normal"><option value="">Select a charge</option>{data.openCharges.map((charge) => <option key={charge.id} value={charge.id}>{charge.period} · due {charge.due_date} · {money.format((Number(charge.amount_cents) - Number(charge.paid_amount_cents)) / 100)}</option>)}</select></label><label className="text-sm font-bold">Payment method<select name="paymentMethod" required className="mt-1 w-full rounded-xl border p-3 font-normal"><option value="cash">Cash</option><option value="cashiers_check">Cashier&apos;s check</option></select></label><label className="text-sm font-bold">Amount received<input name="amount" type="number" min="0.01" step="0.01" required className="mt-1 w-full rounded-xl border p-3 font-normal" /></label><label className="text-sm font-bold">Date received<input name="receivedDate" type="date" required className="mt-1 w-full rounded-xl border p-3 font-normal" /></label><label className="text-sm font-bold">Receipt or check number<input name="receiptReference" className="mt-1 w-full rounded-xl border p-3 font-normal" /></label><label className="text-sm font-bold md:col-span-2">Notes<input name="notes" className="mt-1 w-full rounded-xl border p-3 font-normal" /></label><button disabled={busy || data.openCharges.length === 0} className="rounded-xl bg-slate-950 px-5 py-3 font-bold text-white disabled:opacity-50 md:col-span-2">{busy ? "Saving…" : "Record received payment"}</button></form> : null}
    {showSetup ? <div className="mt-6 rounded-2xl border bg-slate-50 p-5"><h3 className="text-lg font-black">Billing setup</h3><p className="mt-2 font-bold">Stripe: {account === undefined ? "checking…" : label(account?.status || "not connected")}</p>{account?.requirements_due?.length ? <p className="mt-1 text-sm text-amber-800">Stripe still requires {account.requirements_due.length} item(s).</p> : null}<button onClick={connect} disabled={busy || enabled} className="mt-3 rounded-xl bg-slate-950 px-4 py-2 font-bold text-white disabled:opacity-50">{enabled ? "Stripe ready" : account ? "Continue Stripe setup" : "Connect Stripe"}</button><button onClick={() => loadAccount().catch((error) => setMessage(error.message))} className="ml-2 mt-3 rounded-xl border px-4 py-2 font-bold">Refresh status</button><div className="mt-5 border-t pt-4"><h4 className="font-black">Lease activation and charge generation</h4><p className="mt-1 text-sm text-slate-600">Activation starts billing. Monthly charge generation is idempotent.</p>{data.schedules.length === 0 ? <p className="mt-2 text-sm text-slate-500">No saved rent schedule is available.</p> : data.schedules.map((schedule) => <div key={schedule.id} className="mt-3 rounded-xl border bg-white p-4"><p className="font-bold">{money.format(Number(schedule.amount_cents) / 100)} monthly · due day {schedule.due_day} · {label(schedule.status)}</p>{schedule.status === "draft" ? <button type="button" disabled={busy} onClick={() => post({ operation: "activate-lease-schedule", scheduleId: schedule.id }, () => "Lease and rent schedule activated.")} className="mt-3 rounded-xl bg-slate-950 px-4 py-2 font-bold text-white">Activate lease and schedule</button> : null}{schedule.status === "active" ? <form onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); post({ operation: "generate-charge", scheduleId: schedule.id, period: form.get("period") }, (body) => `Rent charge ready for ${body.charge.period}.`); }} className="mt-3 flex items-end gap-3"><label className="text-sm font-bold">Charge month<input name="period" type="month" required defaultValue={new Date().toISOString().slice(0, 7)} className="mt-1 block rounded-xl border p-2 font-normal" /></label><button disabled={busy} className="rounded-xl bg-amber-500 px-4 py-2 font-black">Generate monthly charge</button></form> : null}</div>)}</div></div> : null}
    <RentalRecordBrowser title="Charges and payments" records={records} selectedId={activeId} onSelect={setSelectedId} getTitle={(item) => item.kind === "charge" ? `${item.period} rent charge` : `${money.format(Number(item.amount_cents) / 100)} payment`} getSubtitle={(item) => item.kind === "charge" ? `${label(item.status)} · due ${item.due_date}` : `${label(item.payment_method || item.provider)} · ${label(item.status)}`} emptyMessage="No rent charges or payments recorded.">
      {!selected ? <p className="text-sm text-slate-500">Select a charge or payment to review its details.</p> : <RecordDetail record={selected} onRecordPayment={() => setShowOffline(true)} />}
    </RentalRecordBrowser><a href="/forge/rental/portal" className="mt-6 inline-block font-bold text-amber-800 underline">Open tenant portal</a>
  </section>;
}

function RecordDetail({ record, onRecordPayment }) {
  if (record.kind === "charge") return <div><p className="text-xs font-bold uppercase tracking-widest text-slate-500">Selected charge</p><h3 className="mt-2 text-xl font-black">{record.period} rent</h3><dl className="mt-5 grid gap-4 sm:grid-cols-2"><Fact term="Status" value={label(record.status)} /><Fact term="Due date" value={record.due_date} /><Fact term="Original amount" value={money.format(Number(record.amount_cents) / 100)} /><Fact term="Paid amount" value={money.format(Number(record.paid_amount_cents) / 100)} /><Fact term="Balance" value={money.format((Number(record.amount_cents) - Number(record.paid_amount_cents)) / 100)} /><Fact term="Charge type" value={label(record.charge_type)} /></dl><button type="button" onClick={onRecordPayment} className="mt-6 rounded-xl bg-amber-500 px-4 py-2 font-black">Record payment for an open charge</button></div>;
  return <div><p className="text-xs font-bold uppercase tracking-widest text-slate-500">Selected payment</p><h3 className="mt-2 text-xl font-black">{money.format(Number(record.amount_cents) / 100)} payment</h3><dl className="mt-5 grid gap-4 sm:grid-cols-2"><Fact term="Status" value={label(record.status)} /><Fact term="Method" value={label(record.payment_method || record.provider)} /><Fact term="Received" value={record.received_at ? new Date(record.received_at).toLocaleDateString() : "—"} /><Fact term="Refunded" value={money.format(Number(record.refunded_amount_cents || 0) / 100)} /><Fact term="Receipt" value={record.sourceId} /><Fact term="Settlement" value={record.provider === "stripe" ? label(record.settlement?.status || "awaiting settlement") : "Not applicable"} /></dl></div>;
}
function Fact({ term, value }) { return <div><dt className="text-xs font-bold uppercase text-slate-500">{term}</dt><dd className="mt-1 font-bold capitalize">{value}</dd></div>; }
