"use client";
import {useCallback,useEffect,useState} from "react";
const areas=["Entry","Living room","Kitchen","Primary bedroom","Additional bedrooms","Bathrooms","Laundry","Exterior","Safety devices"];
const labels={move_in:"Move-in",move_out:"Move-out",periodic:"Periodic"};
export function compareInspectionItems(moveInItems=[],moveOutItems=[]){const baseline=new Map(moveInItems.map(item=>[`${item.area}|${item.component}`,item]));return moveOutItems.map(item=>({area:item.area,component:item.component,before:baseline.get(`${item.area}|${item.component}`)?.condition_rating||"not recorded",after:item.condition_rating,changed:(baseline.get(`${item.area}|${item.component}`)?.condition_rating||"not recorded")!==item.condition_rating,damageObserved:item.damage_observed})).filter(item=>item.changed||item.damageObserved);}
export default function RentalInspectionsPanel(){const[data,setData]=useState({inspections:[],items:[],inspectionAcknowledgements:[],schedules:[],units:[],tenants:[]});const[error,setError]=useState("");const[message,setMessage]=useState("");
const load=useCallback(()=>fetch("/api/rental").then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error);setData(body);}),[]);useEffect(()=>{load().catch(reason=>setError(reason.message));},[load]);
async function post(payload){setError("");setMessage("");const response=await fetch("/api/rental",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const body=await response.json();if(!response.ok)throw new Error(body.error);await load();return body;}
async function save(event){event.preventDefault();const form=new FormData(event.currentTarget);const items=areas.map((area,index)=>({area,component:"Overall condition",conditionRating:form.get(`rating-${index}`),notes:form.get(`notes-${index}`),damageObserved:form.get(`damage-${index}`)==="on",depositReviewRecommended:form.get(`review-${index}`)==="on",estimatedCostCents:form.get(`cost-${index}`)?Math.round(Number(form.get(`cost-${index}`))*100):null,evidenceDocumentId:form.get(`evidence-${index}`)||null}));
try{await post({operation:"save-inspection",inspection:{leaseId:form.get("leaseId"),unitId:form.get("unitId"),tenantId:form.get("tenantId"),inspectionType:form.get("inspectionType"),inspectionDate:form.get("inspectionDate"),generalNotes:form.get("generalNotes")},items});event.currentTarget.reset();setMessage("Draft inspection saved. Review it before publishing to the tenant.");}catch(reason){setError(reason.message);}}
async function finalize(id){try{await post({operation:"finalize-inspection",inspectionId:id});setMessage("Inspection finalized and published to the tenant portal.");}catch(reason){setError(reason.message);}}
return <section className="rounded-2xl border bg-white p-6 shadow-sm"><p className="text-sm font-bold uppercase tracking-widest text-amber-700">Condition evidence</p><h2 className="mt-2 text-2xl font-black">Move-in, move-out, and periodic inspections</h2><p className="mt-2 text-slate-600">Document conditions consistently, publish a final record for tenant acknowledgement, and flag possible deposit review. A flag never creates a deduction or decides legal responsibility.</p>
{error?<p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-red-800">{error}</p>:null}{message?<p className="mt-4 rounded-xl bg-emerald-50 p-3 text-emerald-800">{message}</p>:null}
<form onSubmit={save} className="mt-6 space-y-5"><div className="grid gap-3 md:grid-cols-5"><select name="leaseId" required className="rounded-lg border p-3"><option value="">Lease</option>{data.schedules?.map(item=><option key={item.id} value={item.lease_id}>{item.lease_id}</option>)}</select><select name="unitId" required className="rounded-lg border p-3"><option value="">Unit</option>{data.units?.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select><select name="tenantId" required className="rounded-lg border p-3"><option value="">Tenant</option>{data.tenants?.map(item=><option key={item.id} value={item.id}>{item.display_name}</option>)}</select><select name="inspectionType" required defaultValue="move_in" className="rounded-lg border p-3"><option value="move_in">Move-in</option><option value="move_out">Move-out</option><option value="periodic">Periodic</option></select><input name="inspectionDate" type="date" required className="rounded-lg border p-3"/></div>
<div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead><tr className="border-b"><th className="p-2">Area</th><th className="p-2">Condition</th><th className="p-2">Notes</th><th className="p-2">Damage</th><th className="p-2">Deposit review</th><th className="p-2">Estimate</th><th className="p-2">Evidence document ID</th></tr></thead><tbody>{areas.map((area,index)=><tr key={area} className="border-b"><td className="p-2 font-bold">{area}</td><td className="p-2"><select name={`rating-${index}`} defaultValue="not_inspected" className="rounded border p-2"><option value="not_inspected">Not inspected</option><option value="excellent">Excellent</option><option value="good">Good</option><option value="fair">Fair</option><option value="poor">Poor</option><option value="damaged">Damaged</option></select></td><td className="p-2"><input name={`notes-${index}`} className="w-full rounded border p-2"/></td><td className="p-2 text-center"><input name={`damage-${index}`} type="checkbox"/></td><td className="p-2 text-center"><input name={`review-${index}`} type="checkbox"/></td><td className="p-2"><input name={`cost-${index}`} type="number" min="0" step="0.01" className="w-24 rounded border p-2"/></td><td className="p-2"><input name={`evidence-${index}`} className="w-full rounded border p-2"/></td></tr>)}</tbody></table></div><textarea name="generalNotes" placeholder="General inspection notes" className="w-full rounded-lg border p-3"/><button className="w-full rounded-lg bg-slate-950 px-4 py-3 font-bold text-white">Save draft inspection</button></form>
<div className="mt-8 border-t pt-6"><h3 className="font-black">Inspection history</h3><div className="mt-3 space-y-3">{(data.inspections||[]).map(inspection=>{const items=(data.inspectionItems||[]).filter(item=>item.inspection_id===inspection.id);const acknowledged=(data.inspectionAcknowledgements||[]).some(item=>item.inspection_id===inspection.id);const moveIn=(data.inspections||[]).find(item=>item.lease_id===inspection.lease_id&&item.inspection_type==="move_in");const comparison=inspection.inspection_type==="move_out"&&moveIn?compareInspectionItems((data.inspectionItems||[]).filter(item=>item.inspection_id===moveIn.id),items):[];return <article key={inspection.id} className="rounded-xl border p-4"><div className="flex flex-wrap justify-between gap-3"><div><strong>{labels[inspection.inspection_type]} · {inspection.inspection_date}</strong><p className="text-sm capitalize text-slate-500">{inspection.status} · {items.filter(item=>item.damage_observed).length} damage flag(s){acknowledged?" · Tenant acknowledged receipt":""}</p></div>{inspection.status==="draft"?<button onClick={()=>finalize(inspection.id)} className="rounded-lg bg-amber-500 px-4 py-2 font-bold">Finalize and publish</button>:null}</div>{comparison.length?<div className="mt-3 rounded-lg bg-amber-50 p-3 text-sm"><strong>Changes since move-in</strong>{comparison.map(item=><p key={`${item.area}-${item.component}`}>{item.area}: <span className="capitalize">{item.before.replaceAll("_"," ")}</span> → <span className="capitalize">{item.after.replaceAll("_"," ")}</span>{item.damageObserved?" · damage flagged":""}</p>)}</div>:null}</article>;})}{!data.inspections?.length?<p className="text-sm text-slate-500">No rental inspections recorded.</p>:null}</div></div></section>}
