"use client";import{useCallback,useEffect,useState}from"react";const money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"});
const balance=(deposit,transactions)=>transactions.filter(item=>item.deposit_id===deposit.id).reduce((sum,item)=>sum+(["received","adjustment_increase"].includes(item.transaction_type)?1:-1)*Number(item.amount_cents),0);
export default function RentalDepositsPanel(){const[data,setData]=useState({deposits:[],transactions:[],schedules:[],tenants:[]});const[error,setError]=useState("");const[message,setMessage]=useState("");
const load=useCallback(()=>fetch("/api/rental").then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error);setData({deposits:body.deposits||[],transactions:body.depositTransactions||[],schedules:body.schedules||[],tenants:body.tenants||[]});}),[]);useEffect(()=>{load().catch(reason=>setError(reason.message));},[load]);
async function post(payload){setError("");setMessage("");const response=await fetch("/api/rental",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const body=await response.json();if(!response.ok)throw new Error(body.error);await load();}
async function save(event){event.preventDefault();const form=new FormData(event.currentTarget);try{await post({operation:"save-security-deposit",deposit:{leaseId:form.get("leaseId"),tenantId:form.get("tenantId"),requiredAmountCents:Math.round(Number(form.get("amount"))*100),jurisdictionCode:form.get("jurisdictionCode")}});event.currentTarget.reset();setMessage("Security-deposit obligation saved.");}catch(reason){setError(reason.message);}}
async function transact(event){event.preventDefault();const form=new FormData(event.currentTarget);try{await post({operation:"record-security-deposit-transaction",transaction:{depositId:form.get("depositId"),transactionType:form.get("transactionType"),amountCents:Math.round(Number(form.get("amount"))*100),occurredAt:new Date(`${form.get("date")}T12:00:00`).toISOString(),description:form.get("description")}});event.currentTarget.reset();setMessage("Deposit transaction recorded.");}catch(reason){setError(reason.message);}}
return <section className="rounded-2xl border bg-white p-6 shadow-sm"><p className="text-sm font-bold uppercase tracking-widest text-amber-700">Liability accounting</p><h2 className="mt-2 text-2xl font-black">Security deposits</h2><p className="mt-2 text-slate-600">Deposits remain tenant liabilities and are never treated as rent or NOI. Record every receipt, deduction, and refund with supporting evidence.</p>{error?<p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-red-800">{error}</p>:null}{message?<p className="mt-4 rounded-xl bg-emerald-50 p-3 text-emerald-800">{message}</p>:null}
<form onSubmit={save} className="mt-6 grid gap-3 md:grid-cols-4"><select name="leaseId" required className="rounded-lg border p-3"><option value="">Lease</option>{data.schedules.map(item=><option key={item.id} value={item.lease_id}>{item.lease_id}</option>)}</select><select name="tenantId" required className="rounded-lg border p-3"><option value="">Tenant</option>{data.tenants.map(item=><option key={item.id} value={item.id}>{item.display_name}</option>)}</select><input name="amount" type="number" min="0" step="0.01" required placeholder="Required amount" className="rounded-lg border p-3"/><input name="jurisdictionCode" placeholder="Jurisdiction (example TX)" className="rounded-lg border p-3"/><button className="rounded-lg bg-slate-950 px-4 py-3 font-bold text-white md:col-span-4">Save deposit requirement</button></form>
<div className="mt-7 space-y-4">{data.deposits.map(deposit=><article key={deposit.id} className="rounded-xl border p-4"><div className="flex justify-between gap-4"><div><strong>{deposit.id}</strong><p className="text-sm capitalize text-slate-500">{deposit.status.replaceAll("_"," ")} · {deposit.jurisdiction_code||"Jurisdiction not recorded"}</p></div><div className="text-right"><p className="text-sm text-slate-500">Held balance</p><p className="text-xl font-black">{money.format(balance(deposit,data.transactions)/100)}</p><p className="text-xs text-slate-500">Required {money.format(Number(deposit.required_amount_cents)/100)}</p></div></div></article>)}{data.deposits.length===0?<p className="rounded-xl bg-slate-50 p-4 text-slate-600">No deposit obligation recorded.</p>:null}</div>
{data.deposits.length?<form onSubmit={transact} className="mt-7 grid gap-3 border-t pt-6 md:grid-cols-2"><select name="depositId" required className="rounded-lg border p-3"><option value="">Select deposit</option>{data.deposits.map(item=><option key={item.id} value={item.id}>{item.id}</option>)}</select><select name="transactionType" required className="rounded-lg border p-3"><option value="received">Deposit received</option><option value="deduction">Documented deduction</option><option value="refunded">Refund to tenant</option><option value="adjustment_increase">Increase adjustment</option><option value="adjustment_decrease">Decrease adjustment</option></select><input name="amount" type="number" min="0.01" step="0.01" required placeholder="Amount" className="rounded-lg border p-3"/><input name="date" type="date" required className="rounded-lg border p-3"/><input name="description" required placeholder="Reason and evidence reference" className="rounded-lg border p-3 md:col-span-2"/><button className="rounded-lg bg-amber-500 px-4 py-3 font-black md:col-span-2">Record deposit transaction</button></form>:null}
<p className="mt-5 rounded-xl bg-amber-50 p-4 text-sm text-amber-900">Disposition deadlines and allowable deductions depend on jurisdiction and circumstances. FORGE records dates and evidence but does not make the legal determination.</p></section>;}
