"use client";
import { useCallback, useEffect, useState } from "react";
import RentalRecordBrowser from "./RentalRecordBrowser";
const label=(value)=>value?.replaceAll("_"," ")||"—";
export default function RentalDocumentsPanel({initialData=null}){
 const[documents,setDocuments]=useState(initialData?.documents||[]),[schedules,setSchedules]=useState(initialData?.schedules||[]),[selectedId,setSelectedId]=useState(""),[showUpload,setShowUpload]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const load=useCallback(()=>Promise.all([fetch("/api/rental/documents"),fetch("/api/rental")]).then(async([documentResponse,rentalResponse])=>{const documentBody=await documentResponse.json(),rentalBody=await rentalResponse.json();if(!documentResponse.ok)throw new Error(documentBody.error);if(!rentalResponse.ok)throw new Error(rentalBody.error);setDocuments(documentBody.documents||[]);setSchedules(rentalBody.schedules||[]);}),[]);
 useEffect(()=>{if(!initialData)load().catch(reason=>setError(reason.message));},[initialData,load]);
 const activeId=documents.some(item=>item.id===selectedId)?selectedId:documents[0]?.id||"",selected=documents.find(item=>item.id===activeId);
 async function upload(event){event.preventDefault();setError("");setMessage("");const element=event.currentTarget,form=new FormData(element);form.set("tenantVisible",form.get("tenantVisible")==="on"?"true":"false");try{const response=await fetch("/api/rental/documents",{method:"POST",body:form}),body=await response.json();if(!response.ok)throw new Error(body.error);element.reset();await load();setShowUpload(false);setMessage("Document uploaded and access settings saved.");}catch(reason){setError(reason.message);}}
 return <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-widest text-amber-700">Document library</p><h2 className="mt-2 text-2xl font-black">Lease documents and notices</h2><p className="mt-2 text-slate-600">Records stay private unless they are explicitly published to the tenant portal.</p></div><button type="button" onClick={()=>setShowUpload(value=>!value)} className="rounded-xl bg-slate-950 px-4 py-2 font-bold text-white">{showUpload?"Cancel upload":"Upload document"}</button></div>
 {error?<p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-red-800">{error}</p>:null}{message?<p role="status" className="mt-4 rounded-xl bg-emerald-50 p-3 text-emerald-800">{message}</p>:null}
 {showUpload?<form aria-label="Upload rental document" onSubmit={upload} className="mt-6 grid gap-4 rounded-2xl border bg-slate-50 p-5 md:grid-cols-2"><label className="text-sm font-bold">Lease<select name="leaseId" required className="mt-1 w-full rounded-lg border p-3 font-normal"><option value="">Select a lease</option>{schedules.map(schedule=><option key={schedule.id} value={schedule.lease_id}>{schedule.lease_id}</option>)}</select></label><label className="text-sm font-bold">Category<select name="category" required defaultValue="lease" className="mt-1 w-full rounded-lg border p-3 font-normal"><option value="lease">Lease</option><option value="addendum">Addendum</option><option value="notice">Notice</option><option value="inspection">Inspection</option><option value="receipt">Receipt</option><option value="other">Other</option></select></label><label className="text-sm font-bold">Document title<input name="title" required className="mt-1 w-full rounded-lg border p-3 font-normal" placeholder="Signed residential lease"/></label><label className="text-sm font-bold">File<input name="file" type="file" required accept=".pdf,.jpg,.jpeg,.png,.txt" className="mt-1 block w-full rounded-lg border p-3 font-normal"/></label><label className="flex items-center gap-3 rounded-lg bg-blue-50 p-4 text-sm font-bold md:col-span-2"><input type="checkbox" name="tenantVisible"/> Publish this document to the tenant portal</label><button className="rounded-lg bg-slate-950 px-5 py-3 font-bold text-white md:col-span-2">Upload document</button></form>:null}
 <RentalRecordBrowser title="Rental documents" records={documents} selectedId={activeId} onSelect={setSelectedId} getTitle={item=>item.title} getSubtitle={item=>`${label(item.category)} · ${item.tenant_visible?"Published":"Private"}`} emptyMessage="No rental documents uploaded.">
  {!selected?<p className="text-sm text-slate-500">Select a document to review access and acknowledgement details.</p>:<div><p className="text-xs font-bold uppercase tracking-widest text-slate-500">Selected document</p><h3 className="mt-2 text-xl font-black">{selected.title}</h3><dl className="mt-5 grid gap-4 sm:grid-cols-2"><Fact term="Category" value={label(selected.category)}/><Fact term="Publication" value={selected.tenant_visible?"Visible to tenant":"Private to landlord"}/><Fact term="Lease" value={selected.lease_id}/><Fact term="Uploaded" value={selected.created_at?new Date(selected.created_at).toLocaleDateString():"—"}/><Fact term="File" value={selected.original_filename}/><Fact term="Acknowledgements" value={String(selected.acknowledgements?.length||0)}/></dl>{selected.tenant_visible?<p className="mt-5 rounded-xl bg-blue-50 p-3 text-sm font-bold text-blue-900">Published to the tenant portal{selected.published_at?` on ${new Date(selected.published_at).toLocaleDateString()}`:""}.</p>:<p className="mt-5 rounded-xl bg-slate-100 p-3 text-sm font-bold">Private by default. The tenant cannot access this document.</p>}<div className="mt-5"><h4 className="font-black">Tenant acknowledgements</h4>{selected.acknowledgements?.length?selected.acknowledgements.map(item=><p key={`${item.tenant_id}:${item.acknowledged_at}`} className="mt-2 text-sm">Acknowledged {new Date(item.acknowledged_at).toLocaleString()}</p>):<p className="mt-2 text-sm text-slate-500">No tenant acknowledgement recorded.</p>}</div><a href={selected.download_url} target="_blank" rel="noreferrer" className="mt-6 inline-block rounded-xl border px-4 py-2 font-bold text-blue-700">Open document</a></div>}
 </RentalRecordBrowser></section>;
}
function Fact({term,value}){return <div><dt className="text-xs font-bold uppercase text-slate-500">{term}</dt><dd className="mt-1 break-words font-bold capitalize">{value||"—"}</dd></div>}
