"use client";import{useCallback,useState}from"react";import{goldControlClassName}from"@/components/forge/forgeMetallicTheme";
import { useStaleWhileRevalidate } from "@/hooks/useStaleWhileRevalidate";
import { ForgeEmptyState, ForgeErrorState, ForgeLoadingState } from "@/components/forge/ForgeStates";
export default function RentalSupportPanel(){
  // Support cases: stale-while-revalidate. The cached cases render instantly
  // on return visits and refresh in the background — the last good data never
  // blanks out. Mutations post through /api/rental then call refresh() to
  // revalidate. Refund initiation stays a separate, deliberate Stripe action.
  const fetchCases=useCallback(async()=>{const response=await fetch("/api/rental"),body=await response.json();if(!response.ok)throw new Error(body.error);return body.supportCases||[]},[]);
  const{data:cases,error:loadError,isLoading,isRefreshing,refresh}=useStaleWhileRevalidate("rental:support",fetchCases,{ttlMs:60_000});
  const[message,setMessage]=useState("");
  if(!cases&&isLoading)return <ForgeLoadingState label="Loading support cases…" />;
  if(!cases&&loadError)return <ForgeErrorState title="Unable to load support cases" detail={loadError} onRetry={()=>refresh()} />;
  async function update(e,id){e.preventDefault();const f=new FormData(e.currentTarget),r=await fetch("/api/rental",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({operation:"update-support-case",caseId:id,status:f.get("status"),publicNote:f.get("publicNote"),privateNote:f.get("privateNote"),resolution:f.get("resolution")})}),b=await r.json();setMessage(r.ok?"Support case updated.":b.error);if(r.ok)await refresh()}
  return <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-700 dark:bg-slate-900"><p className="text-xs font-black uppercase tracking-[0.2em] text-sky-700 dark:text-sky-400">Operations</p><h2 className="mt-1 text-3xl font-black tracking-tight text-slate-950 dark:text-white">Support and incident cases</h2><p className="mt-2 text-sm text-slate-600 dark:text-slate-400">Failed payments, refunds, and disputes create auditable follow-up without automatically moving money.</p>{cases&&loadError?<p role="status" className="mt-3 text-xs font-bold text-slate-400 dark:text-slate-500">Could not refresh — showing the last saved cases.</p>:null}{cases&&isRefreshing?<p className="mt-3 text-xs font-bold text-slate-400 dark:text-slate-500">Updating…</p>:null}{cases.map(c=><article key={c.id} className="mt-4 rounded-xl border border-slate-200 p-4 dark:border-slate-700"><strong className="text-slate-950 dark:text-white">{c.title}</strong><p className="text-sm text-slate-600 dark:text-slate-400">{c.case_type.replaceAll("_"," ")} · {c.priority} · {c.status.replaceAll("_"," ")}</p><form onSubmit={e=>update(e,c.id)} className="mt-3 grid gap-2"><select name="status" defaultValue={c.status} className="rounded-lg border border-slate-300 bg-white p-2 dark:border-slate-600 dark:bg-slate-900 dark:text-white"><option value="investigating">Investigating</option><option value="waiting_on_tenant">Waiting on tenant</option><option value="waiting_on_provider">Waiting on provider</option><option value="resolved">Resolved</option><option value="closed">Closed</option></select><input name="publicNote" placeholder="Tenant-visible update" className="rounded-lg border border-slate-300 bg-white p-2 dark:border-slate-600 dark:bg-slate-900 dark:text-white"/><input name="privateNote" placeholder="Private owner note" className="rounded-lg border border-slate-300 bg-white p-2 dark:border-slate-600 dark:bg-slate-900 dark:text-white"/><input name="resolution" placeholder="Resolution (required when resolved/closed)" className="rounded-lg border border-slate-300 bg-white p-2 dark:border-slate-600 dark:bg-slate-900 dark:text-white"/><button className={`rounded-lg p-2 text-sm font-bold transition ${goldControlClassName}`}>Save case update</button></form></article>)}{cases.length===0?<ForgeEmptyState headline="No open support cases" guidance="Failed payments, refunds, and disputes will appear here as auditable follow-up." />:null}{message?<p role="status" className="mt-3 text-sm font-bold text-slate-700 dark:text-slate-300">{message}</p>:null}<p className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900 dark:border-amber-900/60 dark:bg-amber-950/30 dark:text-amber-200">Refund initiation remains a separate, deliberate Stripe action. This screen records investigation and resolution evidence only.</p></section>}
