"use client";
import { useCallback, useEffect, useState } from "react";
import RentalRecordBrowser from "./RentalRecordBrowser";
import { goldControlClassName } from "@/components/forge/forgeMetallicTheme";
const label=(value)=>value?.replaceAll("_"," ")||"—",identity=value=>value;
export default function RentalDocumentsPanel({initialData=null,dataScope=identity}){
 const[documents,setDocuments]=useState(initialData?.documents||[]),[schedules,setSchedules]=useState(initialData?.schedules||[]),[selectedId,setSelectedId]=useState(""),[showUpload,setShowUpload]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const load=useCallback(()=>Promise.all([fetch("/api/rental/documents"),fetch("/api/rental")]).then(async([documentResponse,rentalResponse])=>{const documentBody=await documentResponse.json(),rentalBody=await rentalResponse.json();if(!documentResponse.ok)throw new Error(documentBody.error);if(!rentalResponse.ok)throw new Error(rentalBody.error);const scoped=dataScope({...rentalBody,documents:documentBody.documents||[]});setDocuments(scoped.documents||[]);setSchedules(scoped.schedules||[]);}),[dataScope]);
 useEffect(()=>{if(!initialData)load().catch(reason=>setError(reason.message));},[initialData,load]);
 const activeId=documents.some(item=>item.id===selectedId)?selectedId:documents[0]?.id||"",selected=documents.find(item=>item.id===activeId);
 async function upload(event){event.preventDefault();setError("");setMessage("");const element=event.currentTarget,form=new FormData(element);form.set("tenantVisible",form.get("tenantVisible")==="on"?"true":"false");try{const response=await fetch("/api/rental/documents",{method:"POST",body:form}),body=await response.json();if(!response.ok)throw new Error(body.error);element.reset();await load();setShowUpload(false);setMessage("Document uploaded and access settings saved.");}catch(reason){setError(reason.message);}}
 return <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-700 dark:bg-slate-900"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-sky-700 dark:text-sky-400">Document library</p><h2 className="mt-1 text-3xl font-black tracking-tight text-slate-950 dark:text-white">Lease documents and notices</h2><p className="mt-2 text-sm text-slate-600 dark:text-slate-400">Records stay private unless they are explicitly published to the tenant portal.</p></div><button type="button" onClick={()=>setShowUpload(value=>!value)} className={`rounded-xl px-4 py-2 text-sm font-bold transition ${goldControlClassName}`}>{showUpload?"Cancel upload":"Upload document"}</button></div>
 {error?<p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-800 dark:bg-red-950/40 dark:text-red-300">{error}</p>:null}{message?<p role="status" className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm font-bold text-emerald-800 dark:bg-emerald-950/30 dark:text-emerald-300">{message}</p>:null}
 {showUpload?<form aria-label="Upload rental document" onSubmit={upload} className="mt-6 grid gap-4 rounded-2xl border border-slate-200 bg-slate-50 p-5 dark:border-slate-700 dark:bg-slate-950/40 md:grid-cols-2"><label className="text-sm font-bold text-slate-900 dark:text-white">Lease<select name="leaseId" required className="mt-1 w-full rounded-lg border border-slate-300 bg-white p-3 font-normal dark:border-slate-600 dark:bg-slate-900 dark:text-white"><option value="">Select a lease</option>{schedules.map(schedule=><option key={schedule.id} value={schedule.lease_id}>{schedule.lease_id}</option>)}</select></label><label className="text-sm font-bold text-slate-900 dark:text-white">Category<select name="category" required defaultValue="lease" className="mt-1 w-full rounded-lg border border-slate-300 bg-white p-3 font-normal dark:border-slate-600 dark:bg-slate-900 dark:text-white"><option value="lease">Lease</option><option value="addendum">Addendum</option><option value="notice">Notice</option><option value="inspection">Inspection</option><option value="receipt">Receipt</option><option value="other">Other</option></select></label><label className="text-sm font-bold text-slate-900 dark:text-white">Document title<input name="title" required className="mt-1 w-full rounded-lg border border-slate-300 bg-white p-3 font-normal dark:border-slate-600 dark:bg-slate-900 dark:text-white" placeholder="Signed residential lease"/></label><label className="text-sm font-bold text-slate-900 dark:text-white">File<input name="file" type="file" required accept=".pdf,.jpg,.jpeg,.png,.txt" className="mt-1 block w-full rounded-lg border border-slate-300 bg-white p-3 font-normal dark:border-slate-600 dark:bg-slate-900 dark:text-white"/></label><label className="flex items-center gap-3 rounded-lg bg-sky-50 p-4 text-sm font-bold text-sky-950 dark:bg-sky-950/30 dark:text-sky-200 md:col-span-2"><input type="checkbox" name="tenantVisible"/> Publish this document to the tenant portal</label><button className={`rounded-lg px-5 py-3 text-sm font-bold transition md:col-span-2 ${goldControlClassName}`}>Upload document</button></form>:null}
 <div className="mt-6"><RentalRecordBrowser title="Rental documents" records={documents} selectedId={activeId} onSelect={setSelectedId} getTitle={item=>item.title} getSubtitle={item=>`${label(item.category)} · ${item.tenant_visible?"Published":"Private"}`} emptyMessage="No rental documents uploaded.">
  {!selected?<p className="text-sm text-slate-500 dark:text-slate-400">Select a document to review access and acknowledgement details.</p>:<div><p className="text-xs font-bold uppercase tracking-widest text-slate-500 dark:text-slate-400">Selected document</p><h3 className="mt-2 text-xl font-black text-slate-950 dark:text-white">{selected.title}</h3><dl className="mt-5 grid gap-4 sm:grid-cols-2"><Fact term="Category" value={label(selected.category)}/><Fact term="Publication" value={selected.tenant_visible?"Visible to tenant":"Private to landlord"}/><Fact term="Lease" value={selected.lease_id}/><Fact term="Uploaded" value={selected.created_at?new Date(selected.created_at).toLocaleDateString():"—"}/><Fact term="File" value={selected.original_filename}/><Fact term="Acknowledgements" value={String(selected.acknowledgements?.length||0)}/></dl>{selected.tenant_visible?<p className="mt-5 rounded-xl bg-sky-50 p-3 text-sm font-bold text-sky-900 dark:bg-sky-950/30 dark:text-sky-200">Published to the tenant portal{selected.published_at?` on ${new Date(selected.published_at).toLocaleDateString()}`:""}.</p>:<p className="mt-5 rounded-xl bg-slate-100 p-3 text-sm font-bold text-slate-700 dark:bg-slate-800 dark:text-slate-300">Private by default. The tenant cannot access this document.</p>}<div className="mt-5"><h4 className="font-black text-slate-950 dark:text-white">Tenant acknowledgements</h4>{selected.acknowledgements?.length?selected.acknowledgements.map(item=><p key={`${item.tenant_id}:${item.acknowledged_at}`} className="mt-2 text-sm text-slate-700 dark:text-slate-300">Acknowledged {new Date(item.acknowledged_at).toLocaleString()}</p>):<p className="mt-2 text-sm text-slate-500 dark:text-slate-400">No tenant acknowledgement recorded.</p>}</div><a href={selected.download_url} target="_blank" rel="noreferrer" className="mt-6 inline-block rounded-xl border border-slate-300 px-4 py-2 text-sm font-bold text-sky-700 transition hover:bg-sky-50 dark:border-slate-600 dark:text-sky-400 dark:hover:bg-slate-800">Open document</a></div>}
 </RentalRecordBrowser></div></section>;
}
function Fact({term,value}){return <div><dt className="text-xs font-bold uppercase text-slate-500 dark:text-slate-400">{term}</dt><dd className="mt-1 break-words font-bold capitalize text-slate-900 dark:text-white">{value||"—"}</dd></div>}
