"use client";
import{useCallback,useEffect,useMemo,useState}from"react";
const money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"});
export function buildRentalReconciliation(payments,settlements){const byPayment=new Map(settlements.map(value=>[value.payment_id,value]));return payments.map(payment=>{const settlement=byPayment.get(payment.id)||null;let state="not_applicable";
if(payment.provider==="stripe"&&payment.status==="succeeded")state=settlement?settlement.status:"awaiting_settlement";else if(payment.provider==="stripe"&&["failed","disputed"].includes(payment.status))state="attention";
return{payment,settlement,reconciliationState:state};});}
export default function RentalReconciliationPanel(){const[data,setData]=useState({payments:[],settlements:[]});const[error,setError]=useState("");
const load=useCallback(()=>fetch("/api/rental").then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error);setData({payments:body.payments||[],settlements:body.settlements||[]});}),[]);
useEffect(()=>{load().catch(reason=>setError(reason.message));},[load]);const rows=useMemo(()=>buildRentalReconciliation(data.payments,data.settlements),[data]);
return <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-sm font-bold uppercase tracking-widest text-amber-700">Accounting control</p><h2 className="mt-2 text-2xl font-black">Payment reconciliation</h2>
<p className="mt-2 text-slate-600">Successful rent payments post once to FORGE rental income. Refunds and disputes reopen the charge balance and post a separate negative adjustment without deleting the original receipt.</p>
{error?<p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-red-800">{error}</p>:null}<div className="mt-6 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-3">Payment</th><th className="p-3">Amount</th><th className="p-3">Payment status</th><th className="p-3">Reconciliation</th><th className="p-3">Net deposit</th></tr></thead><tbody>{rows.map(({payment,settlement,reconciliationState})=><tr key={payment.id} className="border-b"><td className="p-3 font-mono text-xs">{payment.id}</td><td className="p-3 font-bold">{money.format(payment.amount_cents/100)}</td><td className="p-3 capitalize">{payment.status.replaceAll("_"," ")}</td><td className={`p-3 font-bold capitalize ${reconciliationState==="attention"?"text-red-700":reconciliationState==="awaiting_settlement"?"text-amber-700":"text-slate-700"}`}>{reconciliationState.replaceAll("_"," ")}</td><td className="p-3">{settlement?money.format(settlement.net_amount_cents/100):"—"}</td></tr>)}{rows.length===0?<tr><td colSpan="5" className="p-4 text-slate-500">No rental payments recorded.</td></tr>:null}</tbody></table></div>
<p className="mt-5 rounded-xl bg-amber-50 p-4 text-sm text-amber-900"><strong>Current boundary:</strong> gross rental income posting is implemented. Stripe fees, balance transactions, and bank payout matching must be ingested before a payment is marked fully reconciled.</p></section>;}
