import{describe,expect,it}from"vitest";import{renderToStaticMarkup}from"react-dom/server";import RentalInsurancePanel from"./RentalInsurancePanel.jsx";import RentalDepositsPanel,{depositBalance}from"./RentalDepositsPanel.jsx";import RentalInspectionsPanel,{resolveInspectionLease}from"./RentalInspectionsPanel.jsx";import RentalCommunicationsPanel from"./RentalCommunicationsPanel.jsx";
describe("first-tenant readiness workflows",()=>{
it("renders selected insurance proof for owner review",()=>{const markup=renderToStaticMarkup(<RentalInsurancePanel initialPolicies={[{id:"p1",carrier_name:"Acme Insurance",policy_number_masked:"***1234",liability_limit_cents:10000000,effective_date:"2026-08-01",expiration_date:"2027-08-01",status:"pending_verification"}]}/>);expect(markup).toContain("Selected policy");expect(markup).toContain("Verify proof");expect(markup).toContain("$100,000.00");expect(markup).toContain("Expiration reminders are available for verified policies")});
it("does not claim reminders exist before insurance proof is submitted",()=>{const markup=renderToStaticMarkup(<RentalInsurancePanel initialPolicies={[]}/>);expect(markup).toContain("Expiration reminders become available after");expect(markup).not.toContain("reminders remain queued")});
it("keeps deposit setup and transactions behind deliberate actions",()=>{expect(depositBalance({id:"d1"},[{deposit_id:"d1",transaction_type:"received",amount_cents:100000},{deposit_id:"d1",transaction_type:"refunded",amount_cents:25000}])).toBe(75000);const markup=renderToStaticMarkup(<RentalDepositsPanel initialData={{deposits:[{id:"d1",lease_id:"l1",required_amount_cents:100000,status:"required",jurisdiction_code:"TX"}],transactions:[],schedules:[],tenants:[]}}/>);expect(markup).toContain("Selected deposit");expect(markup).not.toContain('aria-label="Add deposit requirement"');expect(markup).not.toContain('aria-label="Record deposit transaction"')});
it("shows selected inspection while hiding the large creation table",()=>{const markup=renderToStaticMarkup(<RentalInspectionsPanel initialData={{inspections:[{id:"i1",lease_id:"l1",inspection_type:"move_in",inspection_date:"2026-08-13",status:"draft"}],inspectionItems:[],inspectionAcknowledgements:[],schedules:[],units:[],tenants:[]}}/>);expect(markup).toContain("Selected inspection");expect(markup).toContain("Finalize and publish");expect(markup).not.toContain('aria-label="New rental inspection"')});
it("derives the inspection unit and tenants from the selected lease",()=>{const relationship=resolveInspectionLease({leases:[{id:"l1",unit_id:"u1"},{id:"l2",unit_id:"u2"}],units:[{id:"u1",label:"Unit 1"},{id:"u2",label:"Unit 2"}],leaseMemberships:[{lease_id:"l1",tenant_id:"t1"},{lease_id:"l2",tenant_id:"t2"}],tenants:[{id:"t1",display_name:"Lease tenant"},{id:"t2",display_name:"Other tenant"}]},"l1");expect(relationship.unit).toMatchObject({id:"u1"});expect(relationship.tenants).toEqual([{id:"t1",display_name:"Lease tenant"}])});
it("shows selected communication while hiding reminder setup",()=>{const markup=renderToStaticMarkup(<RentalCommunicationsPanel initialData={{notifications:[{id:"n1",subject:"Rent reminder",status:"queued",notification_type:"rent_reminder",recipient:"tenant@example.com",body_text:"Rent is due.",attempt_count:0,max_attempts:3}],charges:[]}}/>);expect(markup).toContain("Selected communication");expect(markup).toContain("Cancel communication");expect(markup).not.toContain('aria-label="Queue rent reminder"')});
});
