"use client";
import{useCallback,useEffect,useState}from"react";
export default function RentalCommunicationsPanel(){
 const[notifications,setNotifications]=useState([]),[charges,setCharges]=useState([]),[error,setError]=useState(""),[message,setMessage]=useState("");
 const load=useCallback(()=>fetch("/api/rental").then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error);setNotifications(b.notifications||[]);setCharges(b.openCharges||[])}),[]);
 useEffect(()=>{load().catch(e=>setError(e.message))},[load]);
 async function post(payload){setError("");const r=await fetch("/api/rental",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),b=await r.json();if(!r.ok)throw new Error(b.error);setMessage("Communication control saved.");await load()}
 function queue(event){event.preventDefault();const f=new FormData(event.currentTarget);post({operation:"queue-rent-reminder",chargeId:f.get("chargeId"),notificationType:f.get("notificationType"),scheduledFor:new Date(f.get("scheduledFor")).toISOString(),maxAttempts:Number(f.get("maxAttempts"))}).catch(e=>setError(e.message))}
 return <section className="rounded-2xl border bg-white p-6 shadow-sm"><p className="text-sm font-bold uppercase tracking-widest text-amber-700">Communications</p><h2 className="mt-2 text-2xl font-black">Notification outbox</h2><p className="mt-2 text-slate-600">Schedule reminders and bounded retries for owner review. Real email sending remains disabled until a provider and sender domain are approved.</p>
 <form onSubmit={queue} className="mt-5 grid gap-3 md:grid-cols-2"><select name="chargeId" required className="rounded-xl border p-3"><option value="">Select open charge</option>{charges.map(c=><option key={c.id} value={c.id}>{c.period} · due {c.due_date}</option>)}</select><select name="notificationType" className="rounded-xl border p-3"><option value="rent_reminder">Upcoming reminder</option><option value="balance_overdue">Overdue balance</option></select><input aria-label="Schedule time" name="scheduledFor" type="datetime-local" required className="rounded-xl border p-3"/><label className="text-sm font-bold">Maximum attempts<input name="maxAttempts" type="number" min="1" max="5" defaultValue="3" className="mt-1 w-full rounded-xl border p-3 font-normal"/></label><button className="rounded-xl bg-slate-950 px-4 py-3 font-bold text-white md:col-span-2">Queue reminder</button></form>
 {error?<p role="alert" className="mt-4 text-red-800">{error}</p>:null}{message?<p role="status" className="mt-4 text-emerald-800">{message}</p>:null}<div className="mt-6 space-y-3">{notifications.length===0?<p>No notifications queued.</p>:notifications.map(n=><article key={n.id} className="rounded-xl border p-4"><strong>{n.subject}</strong><p className="text-sm text-slate-500">To {n.recipient} · {n.notification_type.replaceAll("_"," ")} · {n.status}</p><p className="mt-2 text-sm">{n.body_text}</p>{["queued","failed"].includes(n.status)?<button onClick={()=>post({operation:"cancel-rent-notification",notificationId:n.id}).catch(e=>setError(e.message))} className="mt-3 rounded-lg border px-3 py-2 text-sm font-bold">Cancel</button>:null}</article>)}</div></section>
}
