"use client";
import { useCallback,useEffect,useState } from "react";
export default function TenantDocumentsPanel(){const [documents,setDocuments]=useState([]);const [error,setError]=useState("");const[message,setMessage]=useState("");
  const load=useCallback(()=>fetch("/api/rental/documents").then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error);setDocuments(body.documents||[]);}),[]);
  useEffect(()=>{load().catch(reason=>setError(reason.message));},[load]);
  async function acknowledge(documentId){setError("");setMessage("");try{const response=await fetch("/api/rental/documents",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({operation:"acknowledge-document",documentId})});const body=await response.json();if(!response.ok)throw new Error(body.error);await load();setMessage("Document receipt acknowledged.");}catch(reason){setError(reason.message);}}
  return <section className="rounded-2xl border bg-white p-6 shadow-sm"><p className="text-sm font-bold uppercase tracking-widest text-amber-700">Documents</p><h2 className="mt-2 text-xl font-black">Lease files and notices</h2>
    <p className="mt-2 text-sm text-slate-600">Acknowledging confirms that you received access to a document. It is not an electronic signature and does not mean that you agree with its contents.</p>{message?<p className="mt-3 rounded-xl bg-emerald-50 p-3 text-emerald-800">{message}</p>:null}
    {error?<p role="alert" className="mt-3 text-red-700">{error}</p>:documents.length===0?<p className="mt-3 text-sm text-slate-500">No documents have been published to your portal.</p>:<div className="mt-4 space-y-3">{documents.map(document=>{const acknowledged=document.acknowledgements?.length>0;return <div key={document.id} className="flex flex-wrap items-center justify-between gap-4 rounded-xl border p-4"><div><strong>{document.title}</strong><p className="text-sm capitalize text-slate-500">{document.category} · {document.original_filename}</p>{acknowledged?<p className="mt-1 text-sm font-bold text-emerald-700">Receipt acknowledged</p>:null}</div><div className="flex gap-2"><a href={document.download_url} target="_blank" rel="noreferrer" className="rounded-lg border px-4 py-2 text-sm font-bold">View</a>{!acknowledged?<button onClick={()=>acknowledge(document.id)} className="rounded-lg bg-slate-950 px-4 py-2 text-sm font-bold text-white">Acknowledge receipt</button>:null}</div></div>;})}</div>}
  </section>;}
