import {mapEventRowsForReplay} from "./persistedRowMapping.js";
import {previewExternalManualPayment,previewStripeFeeReimbursement,previewPaymentReversal} from "./adjustmentPreview.js";
import {PRIVATE_FINANCING_EVENT_ORIGIN} from "./privateFinancingContracts.js";
export function projectStripePayment({eventRows,componentRows,termsRows,payment,effectiveDate}){
 const mapped=mapEventRowsForReplay(eventRows,componentRows,termsRows);
 const preview=previewExternalManualPayment({...mapped,asOfDate:effectiveDate,amountCents:Number(payment.amount_cents),eventOrigin:PRIVATE_FINANCING_EVENT_ORIGIN.STRIPE_WEBHOOK,idempotencyKey:`stripe_payment:${payment.provider_mode}:${payment.provider_payment_id}`,acknowledgeOverpayment:false});
 if(!preview.proposedEventPayload)throw new Error(preview.blockingValidation.join(" ")||"Stripe payment cannot be posted.");
 const p=preview.proposedEventPayload;
 return {expectedLedgerSequence:eventRows.reduce((n,e)=>Math.max(n,Number(e.ledger_sequence||0)),0)+1,
  rpcParams:{p_payment_id:payment.id,p_provider_mode:payment.provider_mode,p_expected_ledger_sequence:eventRows.reduce((n,e)=>Math.max(n,Number(e.ledger_sequence||0)),0)+1,p_effective_date:effectiveDate,p_interest_paid_by_component_cents:p.allocation.interestPaidByComponentCents,p_principal_paid_by_component_cents:p.allocation.principalPaidByComponentCents,p_unallocated_cents:p.allocation.unallocatedCents,p_principal_remaining_by_component_cents:p.principalRemainingByComponentCents,p_selected_extra_component_id:p.selectedExtraComponentId||null}};
}
export function projectStripeFeeCredit({eventRows,componentRows,termsRows,payment,feeCents,effectiveDate}){const mapped=mapEventRowsForReplay(eventRows,componentRows,termsRows);const active=[...mapped.componentVersions].filter(c=>c.effectiveDate<=effectiveDate).sort((a,b)=>b.rateBps-a.rateBps||a.allocationPriority-b.allocationPriority)[0];if(!active)throw new Error("No active component for Stripe fee credit.");const preview=previewStripeFeeReimbursement({...mapped,asOfDate:effectiveDate,feeAmountCents:feeCents,postAsLoanCredit:true,componentId:active.componentKey,reason:"Automatic reimbursement of actual Stripe processing fee",borrowerVisibleExplanation:"The seller credited the actual Stripe processing fee to your principal."});if(!preview.proposedEventPayload)throw new Error("Stripe fee credit cannot be posted.");const p=preview.proposedEventPayload,expected=eventRows.reduce((n,e)=>Math.max(n,Number(e.ledger_sequence||0)),0)+1;return{p_payment_id:payment.id,p_provider_mode:payment.provider_mode,p_fee_cents:feeCents,p_expected_ledger_sequence:expected,p_effective_date:effectiveDate,p_component_id:p.componentId,p_corrected_principal_cents:p.correctedComponentPrincipalRemainingCentsAfter};}
export function projectStripeRefund({eventRows,componentRows,termsRows,payment,refundId,effectiveDate}){const mapped=mapEventRowsForReplay(eventRows,componentRows,termsRows);const preview=previewPaymentReversal({...mapped,asOfDate:effectiveDate,reversesEventId:payment.ledger_event_id,reason:"Stripe payment refunded",createdBy:null});if(!preview.proposedEventPayload)throw new Error(preview.blockingValidation.join(" ")||"Stripe refund cannot be posted.");const p=preview.proposedEventPayload,expected=eventRows.reduce((n,e)=>Math.max(n,Number(e.ledger_sequence||0)),0)+1;return{p_payment_id:payment.id,p_provider_mode:payment.provider_mode,p_provider_refund_id:refundId,p_expected_ledger_sequence:expected,p_effective_date:effectiveDate,p_interest_paid_by_component_cents:p.allocation.interestPaidByComponentCents,p_principal_paid_by_component_cents:p.allocation.principalPaidByComponentCents,p_unallocated_cents:p.allocation.unallocatedCents,p_principal_remaining_by_component_cents:p.principalRemainingByComponentCents};}
