import { NextResponse } from "next/server";
import { createAuthenticatedRentalManagerApplication } from "@/lib/supabase/createAuthenticatedRentalManagerApplication";
import { buildAvailabilityCalendar, canReserveRange } from "@/domains/reservations/availability";
import { quoteReservation } from "@/domains/reservations/quote";
import { decodeReservationPreview, encodeReservationPreview } from "@/domains/reservations/previewToken";
const tokenKey=()=>process.env.RESERVATION_PREVIEW_TOKEN_SECRET||process.env.PRIVATE_FINANCING_PREVIEW_TOKEN_SECRET;
const bad=(message,status=400)=>NextResponse.json({error:message},{status});
function inputs(body){return{unitId:String(body?.unitId||"").trim(),guestName:String(body?.guestName||"").trim(),guestEmail:String(body?.guestEmail||"").trim().toLowerCase(),guestPhone:String(body?.guestPhone||"").trim(),checkIn:String(body?.checkIn||""),checkOut:String(body?.checkOut||""),guestCount:Number(body?.guestCount||0),ownerNotes:String(body?.ownerNotes||"").trim()}}
async function compute(authenticated,input,{excludeReservationId=null}={}){const ownerId=authenticated.effectiveOwnerId;const [settings,rates,blocks,reservations]=await Promise.all([
 authenticated.supabaseClient.from("reservation_inventory_settings").select("*").eq("owner_id",ownerId).eq("unit_id",input.unitId).maybeSingle(),
 authenticated.supabaseClient.from("reservation_rate_plans").select("*").eq("owner_id",ownerId).eq("unit_id",input.unitId).eq("status","active"),
 authenticated.supabaseClient.from("reservation_calendar_blocks").select("start_date,end_date,block_type,source_reference").eq("owner_id",ownerId).eq("unit_id",input.unitId),
 authenticated.supabaseClient.from("reservations").select("id,check_in_date,check_out_date,status").eq("owner_id",ownerId).eq("unit_id",input.unitId).in("status",["held","confirmed","checked_in"]),
]);const error=settings.error||rates.error||blocks.error||reservations.error;if(error)throw error;if(!settings.data)throw new Error("Reservable inventory was not found.");const s=settings.data;if(input.guestCount<1||input.guestCount>s.maximum_guests)throw new Error("Guest count is outside the inventory limit.");
 const relevantBlocks=(blocks.data||[]).filter(b=>!excludeReservationId||b.source_reference!==excludeReservationId);
 const relevantReservations=(reservations.data||[]).filter(r=>!excludeReservationId||r.id!==excludeReservationId);
 const allBlocks=[...relevantBlocks.map(b=>({startDate:b.start_date,endDate:b.end_date,blockType:b.block_type})),...relevantReservations.map(r=>({startDate:r.check_in_date,endDate:r.check_out_date,blockType:"reservation"}))];
 const calendar=buildAvailabilityCalendar({rangeStart:input.checkIn,rangeEnd:input.checkOut,blocks:allBlocks,turnoverBufferHours:s.turnover_buffer_hours});const availability=canReserveRange({checkIn:input.checkIn,checkOut:input.checkOut,calendar,minimumNights:s.minimum_nights,maximumNights:s.maximum_nights});if(!availability.allowed)throw new Error("The selected dates are unavailable or outside the stay rules.");
 const quote=quoteReservation({checkIn:input.checkIn,checkOut:input.checkOut,ratePlans:rates.data||[],cleaningFeeCents:s.cleaning_fee_cents,securityDepositCents:s.security_deposit_cents,lodgingTaxBasisPoints:s.lodging_tax_basis_points});return{settings:s,quote};}
export async function GET(){try{const a=await createAuthenticatedRentalManagerApplication();if(a.response)return a.response;const[{data,error},{data:events,error:eventError}]=await Promise.all([a.supabaseClient.from("reservations").select("*,reservation_guests(display_name,email,phone),reservation_inventory_settings(public_name,inventory_type)").eq("owner_id",a.effectiveOwnerId).order("check_in_date"),a.supabaseClient.from("reservation_events").select("*").eq("owner_id",a.effectiveOwnerId).order("occurred_at",{ascending:false})]);if(error||eventError)throw error||eventError;return NextResponse.json({success:true,reservations:data||[],events:events||[]})}catch(error){console.error("Reservation query failed",{name:error?.name||"Error"});return bad("Unable to load reservations.",500)}}
export async function POST(request){try{const a=await createAuthenticatedRentalManagerApplication();if(a.response)return a.response;const body=await request.json();const input=inputs(body);if(!input.unitId||!input.guestName||!input.guestEmail||!input.checkIn||!input.checkOut)return bad("Inventory, guest, email, check-in, and check-out are required.");
 if(body.operation==="preview"){const result=await compute(a,input);const preview={input,quote:result.quote,inventoryName:result.settings.public_name,inventoryType:result.settings.inventory_type};const previewToken=encodeReservationPreview({ownerId:a.effectiveOwnerId,actingUserId:a.user.id,input,quote:result.quote},{key:tokenKey()});return NextResponse.json({success:true,preview,previewToken})}
 if(body.operation!=="confirm"||body.acknowledged!==true||body.confirmationText!=="BOOK")return bad("Preview acknowledgement and typed BOOK confirmation are required.");const token=decodeReservationPreview(body.previewToken,{key:tokenKey()});if(token.ownerId!==a.effectiveOwnerId||token.actingUserId!==a.user.id||JSON.stringify(token.input)!==JSON.stringify(input))return bad("Reservation details changed after preview. Preview again.",409);const fresh=await compute(a,input);if(JSON.stringify(fresh.quote)!==JSON.stringify(token.quote))return bad("Reservation price or availability changed. Preview again.",409);
 const reservationId=`reservation_${token.confirmationId}`,guestId=`reservation_guest_${token.confirmationId}`;const q=fresh.quote;const{data,error}=await a.supabaseClient.rpc("confirm_owner_reservation",{p_owner_id:a.effectiveOwnerId,p_reservation_id:reservationId,p_guest_id:guestId,p_unit_id:input.unitId,p_guest_name:input.guestName,p_guest_email:input.guestEmail,p_guest_phone:input.guestPhone||null,p_check_in_date:input.checkIn,p_check_out_date:input.checkOut,p_guest_count:input.guestCount,p_lodging_amount_cents:q.lodgingAmountCents,p_cleaning_fee_cents:q.cleaningFeeCents,p_lodging_tax_cents:q.lodgingTaxCents,p_security_deposit_cents:q.securityDepositCents,p_total_due_cents:q.totalDueCents,p_currency_code:q.currencyCode,p_source_reference:reservationId,p_owner_notes:input.ownerNotes||null});if(error){if(/no longer available|blocked/i.test(error.message||""))return bad("Reservation dates are no longer available. Preview again.",409);throw error}return NextResponse.json({success:true,reservation:data});
 }catch(error){if(/required|valid|unavailable|inventory|guest count|stay rules|nightly rate|expired/i.test(error?.message||""))return bad(error.message);console.error("Reservation request failed",{name:error?.name||"Error"});return bad("Unable to process reservation.",500)}}

export async function PATCH(request){try{const a=await createAuthenticatedRentalManagerApplication();if(a.response)return a.response;const body=await request.json();const reservationId=String(body?.reservationId||"").trim();if(!reservationId)return bad("Reservation is required.");
 if(["cancel","check_in","check_out"].includes(body.operation)){const{data,error}=await a.supabaseClient.rpc("transition_owner_reservation",{p_owner_id:a.effectiveOwnerId,p_reservation_id:reservationId,p_action:body.operation,p_reason:String(body.reason||"").trim()||null});if(error)throw error;return NextResponse.json({success:true,reservation:data})}
 const input=inputs(body);if(body.operation==="preview_modification"){const result=await compute(a,input,{excludeReservationId:reservationId});const preview={input,quote:result.quote,inventoryName:result.settings.public_name,inventoryType:result.settings.inventory_type};const previewToken=encodeReservationPreview({operation:"modify",reservationId,ownerId:a.effectiveOwnerId,actingUserId:a.user.id,input,quote:result.quote},{key:tokenKey()});return NextResponse.json({success:true,preview,previewToken})}
 if(body.operation!=="confirm_modification"||body.acknowledged!==true||body.confirmationText!=="MODIFY")return bad("Preview acknowledgement and typed MODIFY confirmation are required.");const token=decodeReservationPreview(body.previewToken,{key:tokenKey()});if(token.operation!=="modify"||token.reservationId!==reservationId||token.ownerId!==a.effectiveOwnerId||token.actingUserId!==a.user.id||JSON.stringify(token.input)!==JSON.stringify(input))return bad("Reservation details changed after preview. Preview again.",409);const fresh=await compute(a,input,{excludeReservationId:reservationId});if(JSON.stringify(fresh.quote)!==JSON.stringify(token.quote))return bad("Reservation price or availability changed. Preview again.",409);const q=fresh.quote;const{data,error}=await a.supabaseClient.rpc("modify_owner_reservation",{p_owner_id:a.effectiveOwnerId,p_reservation_id:reservationId,p_unit_id:input.unitId,p_check_in_date:input.checkIn,p_check_out_date:input.checkOut,p_guest_count:input.guestCount,p_lodging_amount_cents:q.lodgingAmountCents,p_cleaning_fee_cents:q.cleaningFeeCents,p_lodging_tax_cents:q.lodgingTaxCents,p_security_deposit_cents:q.securityDepositCents,p_total_due_cents:q.totalDueCents,p_currency_code:q.currencyCode,p_owner_notes:input.ownerNotes||null});if(error)throw error;return NextResponse.json({success:true,reservation:data});
 }catch(error){if(/required|valid|unavailable|inventory|guest count|stay rules|nightly rate|expired|transition|confirmed|not found/i.test(error?.message||""))return bad(error.message);console.error("Reservation lifecycle request failed",{name:error?.name||"Error"});return bad("Unable to update reservation.",500)}}
