// Freshness is derived purely from authority_level, not wall-clock time -- deterministic by
// construction. `current`/`validation_evidence`/`governance_state`/`synchronized_document` are all
// regenerated by the same indexing pass tied to one commit, so they're "current" by definition of
// having just been rebuilt from that commit. `reviewed_decision` (lessons-learned, runbooks) is
// human-authored prose with no automatic regeneration guarantee, so it's "review" -- still
// authoritative where cited, but not proven current. `historical_snapshot` is explicitly historical.
const FRESHNESS_BY_AUTHORITY_LEVEL = Object.freeze({
  current: "current",
  validation_evidence: "current",
  governance_state: "current",
  synchronized_document: "current",
  reviewed_decision: "review",
  historical_snapshot: "stale",
});

export function computeFreshness(record) {
  return FRESHNESS_BY_AUTHORITY_LEVEL[record.authority_level] || "unknown";
}

// Confidence reflects match-signal strength, then is downgraded if the excerpt couldn't be
// independently re-verified against the record's stored content_hash (see resolveExcerpt.mjs) --
// a result is never presented as trustworthy content the indexer can no longer stand behind.
export function computeConfidence(matchSignals, excerptResolution) {
  if (!excerptResolution || !excerptResolution.verified) return "unverifiable";
  if (matchSignals.exactSymbolMatch || matchSignals.exactPathMatch) return "high";
  if (matchSignals.exactPhraseMatch) return "medium";
  if (matchSignals.tokenOverlapCount > 0) return "low";
  return "low";
}
