import{beforeEach,describe,expect,it,vi}from"vitest";const from=vi.fn();
vi.mock("@/lib/supabase/createAuthenticatedForgeApplication",()=>({createAuthenticatedForgeApplication:vi.fn(async()=>({user:{id:"owner_1"},supabaseClient:{from}}))}));
import{GET}from"./route.js";
const tables={
  rental_units:[{id:"u1",label:"Main",status:"occupied",property_id:"kent"},{id:"u2",label:"Second",status:"available",property_id:"rachal"}],
  rental_tenants:[{id:"t1",display_name:"John"},{id:"t2",display_name:"Jane"}],
  rental_leases:[{id:"l1",property_id:"kent",unit_id:"u1",status:"active",start_date:"2026-08-12",end_date:null,monthly_rent_cents:200000},{id:"l2",property_id:"rachal",unit_id:"u2",status:"active",start_date:"2026-08-12",end_date:"2026-09-01",monthly_rent_cents:150000}],
  rental_lease_tenants:[{lease_id:"l1",tenant_id:"t1"},{lease_id:"l2",tenant_id:"t2"}],
  rent_charges:[{lease_id:"l1",status:"overdue",due_date:"2026-08-01",amount_cents:200000,paid_amount_cents:0}],
  rental_payments:[],
  financial_events:[{id:"e1",event_date:"2026-01-01",description:"STARLINK",amount:120,transaction_kind:"expense",normalized_category:"utilities",property_id:"kent"}],
};
describe("rental reports route",()=>{beforeEach(()=>{vi.clearAllMocks();from.mockImplementation(table=>({select:vi.fn(async()=>({data:tables[table],error:null}))}));});
it("returns the owner rental operating report across all properties by default",async()=>{const response=await GET(new Request("https://example.test/api/rental/reports"));const body=await response.json();expect(response.status).toBe(200);expect(body.report.summary.activeLeases).toBe(2);expect(from).toHaveBeenCalledWith("rental_leases");});
it("exports the rent roll as a downloadable CSV",async()=>{const response=await GET(new Request("https://example.test/api/rental/reports?format=csv"));expect(response.headers.get("content-type")).toContain("text/csv");expect(response.headers.get("content-disposition")).toContain("forge-rental-rent-roll");expect(await response.text()).toContain('"Main"');});
it("returns the vacant units report by key",async()=>{const response=await GET(new Request("https://example.test/api/rental/reports?report=vacant-units"));const body=await response.json();expect(response.status).toBe(200);expect(body.report.summary).toMatchObject({vacantUnitCount:0,totalUnitCount:2});});
it("exports a named report as CSV",async()=>{const response=await GET(new Request("https://example.test/api/rental/reports?report=tenant-contacts&format=csv"));expect(response.headers.get("content-type")).toContain("text/csv");expect(response.headers.get("content-disposition")).toContain("forge-rental-tenant-contacts");expect(await response.text()).toContain('"John"');});
it("rejects an unknown report key",async()=>{const response=await GET(new Request("https://example.test/api/rental/reports?report=not-a-report"));expect(response.status).toBe(400);});
it("returns the account ledger report from financial_events instead of the rental tables",async()=>{const response=await GET(new Request("https://example.test/api/rental/reports?report=account-ledger"));const body=await response.json();expect(response.status).toBe(200);expect(body.report.summary).toMatchObject({transactionCount:1,totalDebits:120});expect(from).toHaveBeenCalledWith("financial_events");expect(from).not.toHaveBeenCalledWith("rental_units");});
it("exports the account ledger as CSV",async()=>{const response=await GET(new Request("https://example.test/api/rental/reports?report=account-ledger&format=csv"));expect(response.headers.get("content-type")).toContain("text/csv");expect(response.headers.get("content-disposition")).toContain("forge-account-ledger");expect(await response.text()).toContain('"STARLINK"');});
it("scopes a report to one property and lists every property for the filter dropdown",async()=>{const response=await GET(new Request("https://example.test/api/rental/reports?propertyId=kent"));const body=await response.json();expect(body.report.rentRoll).toHaveLength(1);expect(body.report.rentRoll[0].propertyId).toBe("kent");expect(body.report.availableProperties).toEqual(["kent","rachal"]);});
it("passes asOfDate through to point-in-time reports",async()=>{const before=await GET(new Request("https://example.test/api/rental/reports?report=delinquent-tenants&asOfDate=2026-07-01"));expect((await before.json()).report.summary.delinquentLeaseCount).toBe(0);const after=await GET(new Request("https://example.test/api/rental/reports?report=delinquent-tenants&asOfDate=2026-08-16"));expect((await after.json()).report.summary).toMatchObject({delinquentLeaseCount:1,totalOverdueCents:200000});});
it("passes an explicit start/end date range through to windowed reports",async()=>{const response=await GET(new Request("https://example.test/api/rental/reports?report=lease-expiration&startDate=2026-08-16&endDate=2026-08-20"));const body=await response.json();expect(body.report.rows).toHaveLength(0);const wider=await GET(new Request("https://example.test/api/rental/reports?report=lease-expiration&startDate=2026-08-16&endDate=2026-09-01"));expect((await wider.json()).report.rows.map(row=>row.leaseId)).toEqual(["l2"]);});
});
