import { beforeEach, describe, expect, it, vi } from "vitest";
vi.mock("@/lib/supabase/createAuthenticatedRentalManagerApplication",()=>({createAuthenticatedRentalManagerApplication:vi.fn()}));
import { createAuthenticatedRentalManagerApplication } from "@/lib/supabase/createAuthenticatedRentalManagerApplication";
import { GET, POST, emailDeliveryReadiness } from "./route";

const saved={provider:"resend",sender_name:"FORGE Rentals",sender_email:"rentals@mail.409marketplace.online",verified_domain:"mail.409marketplace.online",status:"active",transactional_enabled:true,reminders_enabled:true};
function database(existing=saved){const single=vi.fn(async()=>({data:saved,error:null})),maybeSingle=vi.fn(async()=>({data:existing,error:null})),query={select:vi.fn().mockReturnThis(),eq:vi.fn().mockReturnThis(),maybeSingle,upsert:vi.fn().mockReturnThis(),single};return{client:{from:vi.fn(()=>query)},query};}
function request(body){return new Request("https://test/api/rental/email-settings",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});}
describe("rental email settings",()=>{
  beforeEach(()=>{vi.clearAllMocks();delete process.env.RESEND_API_KEY;delete process.env.RENTAL_NOTIFICATION_DELIVERY_SECRET;delete process.env.RENTAL_EMAIL_VERIFIED_DOMAIN;});
  it("reports readiness without exposing secrets",()=>{expect(emailDeliveryReadiness({RESEND_API_KEY:"key",RENTAL_NOTIFICATION_DELIVERY_SECRET:"secret",RENTAL_EMAIL_VERIFIED_DOMAIN:"Mail.Example.com"})).toEqual({resendConfigured:true,workerConfigured:true,domainConfigured:true,verifiedDomain:"mail.example.com"});});
  it("loads only the authenticated owner's settings",async()=>{const db=database();createAuthenticatedRentalManagerApplication.mockResolvedValue({user:{id:"owner_1"},supabaseClient:db.client});const response=await GET();expect(response.status).toBe(200);expect(db.query.eq).toHaveBeenCalledWith("owner_id","owner_1");});
  it("saves a fail-closed draft before server configuration is complete",async()=>{const db=database();createAuthenticatedRentalManagerApplication.mockResolvedValue({user:{id:"owner_1"},supabaseClient:db.client});const response=await POST(request({senderName:"FORGE Rentals",senderEmail:"rentals@mail.409marketplace.online",status:"draft",transactionalEnabled:true,remindersEnabled:false}));expect(response.status).toBe(200);expect(db.query.upsert).toHaveBeenCalledWith(expect.objectContaining({owner_id:"owner_1",provider:"resend",status:"draft",reminders_enabled:false}),{onConflict:"owner_id"});});
  it("refuses activation until every server control is configured",async()=>{const db=database();createAuthenticatedRentalManagerApplication.mockResolvedValue({user:{id:"owner_1"},supabaseClient:db.client});expect((await POST(request({senderName:"FORGE Rentals",senderEmail:"rentals@mail.409marketplace.online",status:"active"}))).status).toBe(409);expect(db.query.upsert).not.toHaveBeenCalled();});
  it("refuses a sender outside the verified domain",async()=>{process.env.RESEND_API_KEY="key";process.env.RENTAL_NOTIFICATION_DELIVERY_SECRET="secret";process.env.RENTAL_EMAIL_VERIFIED_DOMAIN="mail.409marketplace.online";const db=database();createAuthenticatedRentalManagerApplication.mockResolvedValue({user:{id:"owner_1"},supabaseClient:db.client});expect((await POST(request({senderName:"FORGE Rentals",senderEmail:"rentals@example.com",status:"active"}))).status).toBe(409);});
});
