alter table rent_charges add column if not exists charge_type text not null default 'rent' check(charge_type in ('rent','proration','late_fee'));
alter table rent_charges add column if not exists related_charge_id text;
alter table rent_charges add constraint rent_charges_related_charge_fk foreign key(owner_id,related_charge_id) references rent_charges(owner_id,id) on delete restrict;
create table if not exists rental_lease_changes(owner_id text not null,id text not null,lease_id text not null,change_type text not null check(change_type in('renewal','amendment','proration')),status text not null default 'draft' check(status in('draft','approved','applied','void')),effective_date date not null,previous_terms jsonb not null,new_terms jsonb not null,reason text not null,document_evidence_id text,approved_at timestamptz,applied_at timestamptz,created_at timestamptz not null default now(),primary key(owner_id,id),foreign key(owner_id,lease_id) references rental_leases(owner_id,id) on delete restrict,foreign key(owner_id,document_evidence_id) references rental_documents(owner_id,id) on delete restrict);
create table if not exists rental_late_fee_rules(owner_id text not null,id text not null,lease_id text not null,status text not null default 'draft' check(status in('draft','active','retired')),jurisdiction_code text not null,grace_days smallint not null check(grace_days between 0 and 31),calculation_type text not null check(calculation_type in('fixed','percentage')),fixed_amount_cents bigint,percentage_basis_points integer,maximum_amount_cents bigint,rule_source text not null,requires_manual_approval boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),primary key(owner_id,id),foreign key(owner_id,lease_id) references rental_leases(owner_id,id) on delete restrict,check((calculation_type='fixed' and fixed_amount_cents>0 and percentage_basis_points is null) or(calculation_type='percentage' and percentage_basis_points>0 and fixed_amount_cents is null)));
create table if not exists rental_late_fee_assessments(owner_id text not null,id text not null,rule_id text not null,lease_id text not null,source_charge_id text not null,fee_charge_id text not null,approved_by text not null,approved_at timestamptz not null,reason text not null,primary key(owner_id,id),unique(owner_id,source_charge_id,rule_id),foreign key(owner_id,rule_id) references rental_late_fee_rules(owner_id,id) on delete restrict,foreign key(owner_id,lease_id) references rental_leases(owner_id,id) on delete restrict,foreign key(owner_id,source_charge_id) references rent_charges(owner_id,id) on delete restrict,foreign key(owner_id,fee_charge_id) references rent_charges(owner_id,id) on delete restrict);
alter table rental_lease_changes enable row level security;alter table rental_lease_changes force row level security;alter table rental_late_fee_rules enable row level security;alter table rental_late_fee_rules force row level security;alter table rental_late_fee_assessments enable row level security;alter table rental_late_fee_assessments force row level security;
create policy "rental_lease_change_owner_all" on rental_lease_changes for all to authenticated using(owner_id=auth.uid()::text) with check(owner_id=auth.uid()::text);create policy "rental_lease_change_tenant_select" on rental_lease_changes for select to authenticated using(status='applied' and rental_actor_has_lease_access(owner_id,lease_id));
create policy "rental_late_rule_owner_all" on rental_late_fee_rules for all to authenticated using(owner_id=auth.uid()::text) with check(owner_id=auth.uid()::text);create policy "rental_late_rule_tenant_select" on rental_late_fee_rules for select to authenticated using(status='active' and rental_actor_has_lease_access(owner_id,lease_id));
create policy "rental_late_assessment_owner_all" on rental_late_fee_assessments for all to authenticated using(owner_id=auth.uid()::text) with check(owner_id=auth.uid()::text);create policy "rental_late_assessment_tenant_select" on rental_late_fee_assessments for select to authenticated using(rental_actor_has_lease_access(owner_id,lease_id));
create or replace function apply_rental_lease_change(p_owner_id text,p_change_id text)returns jsonb language plpgsql security invoker set search_path=public as $$
declare c rental_lease_changes%rowtype;l rental_leases%rowtype;s rent_schedules%rowtype;new_schedule_id text;amount bigint;due_day smallint;
begin if p_owner_id<>auth.uid()::text then raise exception 'Authenticated owner does not match lease owner.';end if;select * into c from rental_lease_changes where owner_id=p_owner_id and id=p_change_id for update;if not found or c.status<>'approved' then raise exception 'Approved lease change was not found.';end if;select * into l from rental_leases where owner_id=p_owner_id and id=c.lease_id for update;select * into s from rent_schedules where owner_id=p_owner_id and lease_id=l.id and status='active' order by effective_start_date desc limit 1 for update;
if c.change_type in('renewal','amendment') then amount:=coalesce((c.new_terms->>'monthlyRentCents')::bigint,l.monthly_rent_cents);due_day:=coalesce((c.new_terms->>'rentDueDay')::smallint,l.rent_due_day);if s.id is not null then update rent_schedules set status='ended',effective_end_date=c.effective_date-1,updated_at=now() where owner_id=p_owner_id and id=s.id;end if;new_schedule_id:='rent_schedule_'||gen_random_uuid()::text;insert into rent_schedules(owner_id,id,lease_id,status,amount_cents,currency_code,due_day,effective_start_date,effective_end_date)values(p_owner_id,new_schedule_id,l.id,'active',amount,l.currency_code,due_day,c.effective_date,nullif(c.new_terms->>'endDate','')::date);update rental_leases set end_date=coalesce(nullif(c.new_terms->>'endDate','')::date,end_date),monthly_rent_cents=amount,rent_due_day=due_day,updated_at=now() where owner_id=p_owner_id and id=l.id;
else amount:=(c.new_terms->>'amountCents')::bigint;if amount<=0 then raise exception 'Approved proration requires a positive amount.';end if;if s.id is null then raise exception 'An active schedule is required for proration.';end if;insert into rent_charges(owner_id,id,lease_id,schedule_id,period,due_date,amount_cents,paid_amount_cents,currency_code,status,source_key,notes,charge_type)values(p_owner_id,'rent_charge_proration_'||c.id,l.id,s.id,to_char(c.effective_date,'YYYY-MM'),c.effective_date,amount,0,l.currency_code,case when c.effective_date>current_date then 'scheduled' else 'due' end,'proration:'||c.id,c.reason,'proration');end if;
update rental_lease_changes set status='applied',applied_at=now() where owner_id=p_owner_id and id=c.id;return jsonb_build_object('changeId',c.id,'status','applied','scheduleId',new_schedule_id);end;$$;
create or replace function assess_rental_late_fee(p_owner_id text,p_rule_id text,p_charge_id text,p_reason text)returns jsonb language plpgsql security invoker set search_path=public as $$
declare r rental_late_fee_rules%rowtype;c rent_charges%rowtype;fee bigint;fee_id text:='rent_charge_late_'||gen_random_uuid()::text;a_id text:='rental_late_assessment_'||gen_random_uuid()::text;
begin if p_owner_id<>auth.uid()::text then raise exception 'Authenticated owner does not match lease owner.';end if;select * into r from rental_late_fee_rules where owner_id=p_owner_id and id=p_rule_id and status='active' for update;if not found or not r.requires_manual_approval then raise exception 'An active manually approved late-fee rule is required.';end if;select * into c from rent_charges where owner_id=p_owner_id and id=p_charge_id and lease_id=r.lease_id for update;if not found or c.status in('paid','void') or c.due_date+r.grace_days>=current_date then raise exception 'Charge is not eligible for a late fee.';end if;fee:=case when r.calculation_type='fixed' then r.fixed_amount_cents else ceil((c.amount_cents-c.paid_amount_cents)*r.percentage_basis_points/10000.0)::bigint end;fee:=least(fee,coalesce(r.maximum_amount_cents,fee));insert into rent_charges(owner_id,id,lease_id,schedule_id,period,due_date,amount_cents,paid_amount_cents,currency_code,status,source_key,notes,charge_type,related_charge_id)values(p_owner_id,fee_id,c.lease_id,c.schedule_id,to_char(current_date,'YYYY-MM'),current_date,fee,0,c.currency_code,'due','latefee:'||r.id||':'||c.id,p_reason,'late_fee',c.id);insert into rental_late_fee_assessments(owner_id,id,rule_id,lease_id,source_charge_id,fee_charge_id,approved_by,approved_at,reason)values(p_owner_id,a_id,r.id,c.lease_id,c.id,fee_id,auth.uid()::text,now(),btrim(p_reason));return jsonb_build_object('assessmentId',a_id,'feeChargeId',fee_id,'amountCents',fee);end;$$;
revoke all on function apply_rental_lease_change(text,text),function assess_rental_late_fee(text,text,text,text) from public,anon;grant execute on function apply_rental_lease_change(text,text),function assess_rental_late_fee(text,text,text,text) to authenticated;
