create table if not exists rental_lease_preparations(
 owner_id text not null,id text not null,lease_id text not null,title text not null,status text not null default 'draft' check(status in('draft','approved','superseded')),current_version integer not null default 0,approved_version integer,approved_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),primary key(owner_id,id),unique(owner_id,lease_id),foreign key(owner_id,lease_id) references rental_leases(owner_id,id) on delete restrict,check(approved_version is null or approved_version between 1 and current_version));
create table if not exists rental_lease_preparation_versions(
 owner_id text not null,preparation_id text not null,version_number integer not null check(version_number>0),terms jsonb not null check(jsonb_typeof(terms)='object'),change_summary text not null,created_by text not null,created_at timestamptz not null default now(),primary key(owner_id,preparation_id,version_number),foreign key(owner_id,preparation_id) references rental_lease_preparations(owner_id,id) on delete restrict);
create index if not exists idx_rental_lease_preparation_lease on rental_lease_preparations(owner_id,lease_id);
alter table rental_lease_preparations enable row level security;alter table rental_lease_preparations force row level security;alter table rental_lease_preparation_versions enable row level security;alter table rental_lease_preparation_versions force row level security;
create policy "rental_lease_preparation_owner_all" on rental_lease_preparations for all to authenticated using(owner_id=auth.uid()::text) with check(owner_id=auth.uid()::text);
create policy "rental_lease_preparation_tenant_select" on rental_lease_preparations for select to authenticated using(status='approved' and rental_actor_has_lease_access(owner_id,lease_id));
create policy "rental_lease_preparation_version_owner_all" on rental_lease_preparation_versions for all to authenticated using(owner_id=auth.uid()::text) with check(owner_id=auth.uid()::text);
create policy "rental_lease_preparation_version_tenant_select" on rental_lease_preparation_versions for select to authenticated using(exists(select 1 from rental_lease_preparations p where p.owner_id=rental_lease_preparation_versions.owner_id and p.id=rental_lease_preparation_versions.preparation_id and p.status='approved' and p.approved_version=rental_lease_preparation_versions.version_number and rental_actor_has_lease_access(p.owner_id,p.lease_id)));
create or replace function save_rental_lease_preparation_version(p_owner_id text,p_lease_id text,p_title text,p_terms jsonb,p_change_summary text)returns jsonb language plpgsql security invoker set search_path=public as $$
declare p rental_lease_preparations%rowtype;next_version integer;
begin if p_owner_id<>auth.uid()::text then raise exception 'Authenticated owner does not match lease owner.';end if;if jsonb_typeof(p_terms)<>'object' then raise exception 'Lease preparation terms must be an object.';end if;
select * into p from rental_lease_preparations where owner_id=p_owner_id and lease_id=p_lease_id for update;
if not found then insert into rental_lease_preparations(owner_id,id,lease_id,title)values(p_owner_id,'rental_lease_preparation_'||gen_random_uuid()::text,p_lease_id,p_title)returning * into p;end if;
next_version:=p.current_version+1;insert into rental_lease_preparation_versions(owner_id,preparation_id,version_number,terms,change_summary,created_by)values(p_owner_id,p.id,next_version,p_terms,p_change_summary,auth.uid()::text);
update rental_lease_preparations set title=p_title,status='draft',current_version=next_version,approved_version=null,approved_at=null,updated_at=now() where owner_id=p_owner_id and id=p.id;
return jsonb_build_object('preparationId',p.id,'leaseId',p_lease_id,'versionNumber',next_version,'status','draft');end;$$;
create or replace function approve_rental_lease_preparation_version(p_owner_id text,p_preparation_id text,p_version_number integer)returns jsonb language plpgsql security invoker set search_path=public as $$
begin if p_owner_id<>auth.uid()::text then raise exception 'Authenticated owner does not match lease owner.';end if;
if not exists(select 1 from rental_lease_preparation_versions where owner_id=p_owner_id and preparation_id=p_preparation_id and version_number=p_version_number)then raise exception 'Lease preparation version was not found.';end if;
update rental_lease_preparations set status='approved',approved_version=p_version_number,approved_at=now(),updated_at=now() where owner_id=p_owner_id and id=p_preparation_id;
if not found then raise exception 'Lease preparation was not found.';end if;return jsonb_build_object('preparationId',p_preparation_id,'versionNumber',p_version_number,'status','approved');end;$$;
revoke all on function save_rental_lease_preparation_version(text,text,text,jsonb,text) from public,anon;grant execute on function save_rental_lease_preparation_version(text,text,text,jsonb,text) to authenticated;
revoke all on function approve_rental_lease_preparation_version(text,text,integer) from public,anon;grant execute on function approve_rental_lease_preparation_version(text,text,integer) to authenticated;
