create table if not exists rental_contractors(owner_id text not null,id text not null,business_name text not null,contact_name text,email text,phone text,status text not null default 'active' check(status in('active','inactive','do_not_use')),trade text,license_reference text,insurance_expiration date,w9_status text not null default 'not_requested' check(w9_status in('not_requested','requested','received','reviewed')),tax_classification text,tax_id_last4 text check(tax_id_last4 is null or tax_id_last4~'^\d{4}$'),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),primary key(owner_id,id));
create table if not exists rental_maintenance_work_orders(owner_id text not null,id text not null,request_id text not null,contractor_id text,status text not null default 'draft' check(status in('draft','assigned','scheduled','in_progress','completed','cancelled')),scope_of_work text not null,scheduled_start timestamptz,scheduled_end timestamptz,entry_instructions text,estimated_cost_cents bigint check(estimated_cost_cents is null or estimated_cost_cents>=0),actual_cost_cents bigint check(actual_cost_cents is null or actual_cost_cents>=0),invoice_reference text,invoice_document_id text,completion_document_id text,completed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),primary key(owner_id,id),foreign key(owner_id,request_id) references rental_maintenance_requests(owner_id,id) on delete restrict,foreign key(owner_id,contractor_id) references rental_contractors(owner_id,id) on delete restrict,foreign key(owner_id,invoice_document_id) references rental_documents(owner_id,id) on delete restrict,foreign key(owner_id,completion_document_id) references rental_documents(owner_id,id) on delete restrict,check(scheduled_end is null or scheduled_start is not null and scheduled_end>=scheduled_start));
create table if not exists rental_maintenance_work_events(owner_id text not null,id text not null,work_order_id text not null,event_type text not null check(event_type in('created','assigned','scheduled','started','note','cost_recorded','completed','cancelled')),public_note text,private_note text,occurred_at timestamptz not null default now(),recorded_by text not null,primary key(owner_id,id),foreign key(owner_id,work_order_id) references rental_maintenance_work_orders(owner_id,id) on delete restrict);
create index if not exists idx_rental_work_order_request on rental_maintenance_work_orders(owner_id,request_id,created_at);create index if not exists idx_rental_work_event_order on rental_maintenance_work_events(owner_id,work_order_id,occurred_at);
alter table rental_contractors enable row level security;alter table rental_contractors force row level security;alter table rental_maintenance_work_orders enable row level security;alter table rental_maintenance_work_orders force row level security;alter table rental_maintenance_work_events enable row level security;alter table rental_maintenance_work_events force row level security;
create policy "rental_contractor_owner_all" on rental_contractors for all to authenticated using(owner_id=auth.uid()::text) with check(owner_id=auth.uid()::text);
create policy "rental_work_order_owner_all" on rental_maintenance_work_orders for all to authenticated using(owner_id=auth.uid()::text) with check(owner_id=auth.uid()::text);
create policy "rental_work_event_owner_all" on rental_maintenance_work_events for all to authenticated using(owner_id=auth.uid()::text) with check(owner_id=auth.uid()::text);
create or replace function create_rental_maintenance_work_order(p_owner_id text,p_work_order jsonb)returns jsonb language plpgsql security invoker set search_path=public as $$
declare w rental_maintenance_work_orders%rowtype;request_id text:=p_work_order->>'requestId';contractor_id text:=nullif(p_work_order->>'contractorId','');
begin if p_owner_id<>auth.uid()::text then raise exception 'Authenticated owner does not match work-order owner.';end if;
if not exists(select 1 from rental_maintenance_requests where owner_id=p_owner_id and id=request_id)then raise exception 'Maintenance request was not found.';end if;
if contractor_id is not null and not exists(select 1 from rental_contractors where owner_id=p_owner_id and id=contractor_id and status='active')then raise exception 'Active contractor was not found.';end if;
insert into rental_maintenance_work_orders(owner_id,id,request_id,contractor_id,status,scope_of_work,scheduled_start,scheduled_end,entry_instructions,estimated_cost_cents)
values(p_owner_id,p_work_order->>'id',request_id,contractor_id,case when contractor_id is null then'draft'else'assigned'end,p_work_order->>'scopeOfWork',nullif(p_work_order->>'scheduledStart','')::timestamptz,nullif(p_work_order->>'scheduledEnd','')::timestamptz,nullif(btrim(p_work_order->>'entryInstructions'),''),nullif(p_work_order->>'estimatedCostCents','')::bigint)returning * into w;
insert into rental_maintenance_work_events(owner_id,id,work_order_id,event_type,public_note,private_note,recorded_by)values(p_owner_id,'rental_work_event_'||gen_random_uuid()::text,w.id,case when contractor_id is null then'created'else'assigned'end,nullif(btrim(p_work_order->>'publicNote'),''),nullif(btrim(p_work_order->>'privateNote'),''),auth.uid()::text);
return to_jsonb(w);end;$$;
create or replace function load_rental_maintenance_work_updates(p_lease_id text)returns jsonb language sql stable security definer set search_path=public set row_security=off as $$
select coalesce(jsonb_agg(jsonb_build_object('id',w.id,'requestId',w.request_id,'status',w.status,'scheduledStart',w.scheduled_start,'scheduledEnd',w.scheduled_end,'updates',coalesce((select jsonb_agg(jsonb_build_object('id',e.id,'eventType',e.event_type,'publicNote',e.public_note,'occurredAt',e.occurred_at)order by e.occurred_at desc)from rental_maintenance_work_events e where e.owner_id=w.owner_id and e.work_order_id=w.id and e.public_note is not null),'[]'::jsonb))order by w.created_at desc),'[]'::jsonb)
from rental_maintenance_work_orders w join rental_maintenance_requests r on r.owner_id=w.owner_id and r.id=w.request_id where r.lease_id=p_lease_id and rental_actor_has_lease_access(r.owner_id,r.lease_id);$$;
create or replace function update_rental_maintenance_work_order(p_owner_id text,p_work_order_id text,p_status text,p_scheduled_start timestamptz,p_scheduled_end timestamptz,p_estimated_cost_cents bigint,p_actual_cost_cents bigint,p_invoice_reference text,p_invoice_document_id text,p_completion_document_id text,p_public_note text,p_private_note text)returns jsonb language plpgsql security invoker set search_path=public as $$
declare w rental_maintenance_work_orders%rowtype;e text;
begin if p_owner_id<>auth.uid()::text then raise exception 'Authenticated owner does not match work-order owner.';end if;if p_status not in('assigned','scheduled','in_progress','completed','cancelled') then raise exception 'Unsupported work-order status.';end if;select * into w from rental_maintenance_work_orders where owner_id=p_owner_id and id=p_work_order_id for update;if not found then raise exception 'Work order was not found.';end if;e:=case p_status when'assigned'then'assigned' when'scheduled'then'scheduled' when'in_progress'then'started' when'completed'then'completed' else'cancelled'end;update rental_maintenance_work_orders set status=p_status,scheduled_start=coalesce(p_scheduled_start,scheduled_start),scheduled_end=coalesce(p_scheduled_end,scheduled_end),estimated_cost_cents=coalesce(p_estimated_cost_cents,estimated_cost_cents),actual_cost_cents=coalesce(p_actual_cost_cents,actual_cost_cents),invoice_reference=coalesce(nullif(btrim(p_invoice_reference),''),invoice_reference),invoice_document_id=coalesce(p_invoice_document_id,invoice_document_id),completion_document_id=coalesce(p_completion_document_id,completion_document_id),completed_at=case when p_status='completed' then now() else completed_at end,updated_at=now() where owner_id=p_owner_id and id=p_work_order_id;insert into rental_maintenance_work_events(owner_id,id,work_order_id,event_type,public_note,private_note,recorded_by)values(p_owner_id,'rental_work_event_'||gen_random_uuid()::text,p_work_order_id,e,nullif(btrim(p_public_note),''),nullif(btrim(p_private_note),''),auth.uid()::text);return jsonb_build_object('workOrderId',p_work_order_id,'status',p_status);end;$$;
revoke all on function update_rental_maintenance_work_order(text,text,text,timestamptz,timestamptz,bigint,bigint,text,text,text,text,text) from public,anon;grant execute on function update_rental_maintenance_work_order(text,text,text,timestamptz,timestamptz,bigint,bigint,text,text,text,text,text) to authenticated;
revoke all on function create_rental_maintenance_work_order(text,jsonb) from public,anon;grant execute on function create_rental_maintenance_work_order(text,jsonb) to authenticated;
revoke all on function load_rental_maintenance_work_updates(text) from public,anon;grant execute on function load_rental_maintenance_work_updates(text) to authenticated;
