create table if not exists renters_insurance_evidence(owner_id text not null,id text not null,tenant_id text not null,lease_id text not null,bucket text not null default 'rental-insurance-evidence',object_path text not null,original_filename text not null,mime_type text not null,byte_size bigint not null check(byte_size between 1 and 10485760),created_at timestamptz not null default now(),primary key(owner_id,id),unique(bucket,object_path),foreign key(owner_id,tenant_id)references rental_tenants(owner_id,id),foreign key(owner_id,lease_id)references rental_leases(owner_id,id));
alter table renters_insurance_evidence enable row level security;alter table renters_insurance_evidence force row level security;
create policy insurance_evidence_owner_read on renters_insurance_evidence for select to authenticated using(owner_id=auth.uid()::text);
create policy insurance_evidence_tenant_insert on renters_insurance_evidence for insert to authenticated with check(exists(select 1 from rental_tenants t join rental_lease_tenants m on m.owner_id=t.owner_id and m.tenant_id=t.id where t.auth_user_id=auth.uid()and t.owner_id=renters_insurance_evidence.owner_id and t.id=renters_insurance_evidence.tenant_id and m.lease_id=renters_insurance_evidence.lease_id));
create policy insurance_evidence_tenant_read on renters_insurance_evidence for select to authenticated using(exists(select 1 from rental_tenants t where t.auth_user_id=auth.uid()and t.owner_id=renters_insurance_evidence.owner_id and t.id=renters_insurance_evidence.tenant_id));
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)values('rental-insurance-evidence','rental-insurance-evidence',false,10485760,array['application/pdf','image/jpeg','image/png'])on conflict(id)do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;

create or replace function submit_renters_insurance_policy(p_lease_id text,p_carrier_name text,p_policy_number_masked text,p_liability_limit_cents bigint,p_effective_date date,p_expiration_date date,p_evidence_id text)returns renters_insurance_policies language plpgsql security invoker set search_path=public as $$declare t rental_tenants;result renters_insurance_policies;begin select tenant.* into t from rental_tenants tenant join rental_lease_tenants m on m.owner_id=tenant.owner_id and m.tenant_id=tenant.id where tenant.auth_user_id=auth.uid()and m.lease_id=p_lease_id limit 1;if t.id is null then raise exception 'Tenant lease access is required.';end if;if p_expiration_date<p_effective_date or p_liability_limit_cents<0 then raise exception 'Policy dates or limit are invalid.';end if;if not exists(select 1 from renters_insurance_evidence e where e.owner_id=t.owner_id and e.id=p_evidence_id and e.tenant_id=t.id and e.lease_id=p_lease_id)then raise exception 'Matching policy evidence is required.';end if;insert into renters_insurance_policies(owner_id,id,tenant_id,lease_id,carrier_name,policy_number_masked,liability_limit_cents,effective_date,expiration_date,status,evidence_id,last_checked_at)values(t.owner_id,'renters_policy_'||gen_random_uuid()::text,t.id,p_lease_id,btrim(p_carrier_name),btrim(p_policy_number_masked),p_liability_limit_cents,p_effective_date,p_expiration_date,'pending_verification',p_evidence_id,now())returning * into result;return result;end$$;
grant execute on function submit_renters_insurance_policy(text,text,text,bigint,date,date,text)to authenticated;

create or replace function review_renters_insurance_policy(p_owner_id text,p_policy_id text,p_decision text,p_note text)returns renters_insurance_policies language plpgsql security invoker set search_path=public as $$declare result renters_insurance_policies;begin if p_owner_id<>auth.uid()::text or p_decision not in('verified','rejected')then raise exception 'Owner review is invalid.';end if;update renters_insurance_policies set status=p_decision,verification_provider='owner_review',verified_at=case when p_decision='verified'then now()else null end,last_checked_at=now(),updated_at=now()where owner_id=p_owner_id and id=p_policy_id and status='pending_verification'returning * into result;if result.id is null then raise exception 'Pending policy was not found.';end if;return result;end$$;
grant execute on function review_renters_insurance_policy(text,text,text,text)to authenticated;
create or replace function queue_renters_insurance_renewal_reminders(p_owner_id text,p_as_of date default current_date)returns integer language plpgsql security invoker set search_path=public as $$declare count_rows integer;begin if p_owner_id<>auth.uid()::text then raise exception 'Owner identity mismatch.';end if;insert into rental_notification_outbox(owner_id,id,tenant_id,lease_id,event_key,notification_type,recipient,subject,body_text,status,scheduled_for,max_attempts)select p.owner_id,'rental_notification_'||gen_random_uuid()::text,p.tenant_id,p.lease_id,'insurance:'||p.id||':'||(p.expiration_date-p_as_of)::text,'document_published',t.email,'Renters insurance renewal reminder','Your renters insurance policy expires on '||p.expiration_date||'. Submit renewed proof in your FORGE tenant portal.','queued',now(),3 from renters_insurance_policies p join rental_tenants t on t.owner_id=p.owner_id and t.id=p.tenant_id where p.owner_id=p_owner_id and p.status='verified'and p.expiration_date-p_as_of in(30,7)on conflict(event_key)do nothing;get diagnostics count_rows=row_count;return count_rows;end$$;
grant execute on function queue_renters_insurance_renewal_reminders(text,date)to authenticated;
