create or replace function request_rental_animal(p_lease_id text,p_name text,p_breed_description text,p_request_type text)returns rental_animals language plpgsql security invoker set search_path=public as $$declare t rental_tenants;result rental_animals;begin select tenant.* into t from rental_tenants tenant join rental_lease_tenants m on m.owner_id=tenant.owner_id and m.tenant_id=tenant.id where tenant.auth_user_id=auth.uid()and m.lease_id=p_lease_id limit 1;if t.id is null then raise exception 'Tenant lease access is required.';end if;if p_request_type not in('pet','assistance_review_requested')then raise exception 'Animal request type is invalid.';end if;insert into rental_animals(owner_id,id,tenant_id,lease_id,name,species,breed_description,classification,human_review_required,approval_status)values(t.owner_id,'rental_animal_'||gen_random_uuid()::text,t.id,p_lease_id,btrim(p_name),'dog',btrim(p_breed_description),p_request_type,true,'requested')returning * into result;return result;end$$;
grant execute on function request_rental_animal(text,text,text,text)to authenticated;

create or replace function review_rental_animal(p_owner_id text,p_animal_id text,p_decision text,p_classification text,p_approval_evidence_id text,p_monthly_fee_cents bigint default null,p_effective_start_date date default null)returns jsonb language plpgsql security invoker set search_path=public as $$declare a rental_animals;fee monthly_pet_fees;begin if p_owner_id<>auth.uid()::text or p_decision not in('approved','denied')then raise exception 'Owner animal review is invalid.';end if;select * into a from rental_animals where owner_id=p_owner_id and id=p_animal_id for update;if a.id is null then raise exception 'Animal request was not found.';end if;
if a.classification='assistance_review_requested' then if p_classification not in('assistance_animal_approved','assistance_request_denied')then raise exception 'Assistance request requires a human classification decision.';end if;if p_monthly_fee_cents is not null then raise exception 'Pet fees cannot be assigned through an assistance-animal review.';end if;update rental_animals set classification=p_classification,approval_status=p_decision,approved_at=case when p_decision='approved'then now()else null end,approved_by=case when p_decision='approved'then p_owner_id else null end,approval_evidence_id=case when p_decision='approved'then p_approval_evidence_id else null end,human_review_required=false,updated_at=now()where owner_id=p_owner_id and id=a.id;
else if p_classification<>'pet'then raise exception 'Pet review cannot change to an assistance classification.';end if;update rental_animals set approval_status=p_decision,approved_at=case when p_decision='approved'then now()else null end,approved_by=case when p_decision='approved'then p_owner_id else null end,approval_evidence_id=case when p_decision='approved'then p_approval_evidence_id else null end,updated_at=now()where owner_id=p_owner_id and id=a.id;if p_decision='approved'and p_monthly_fee_cents is not null then if p_monthly_fee_cents<=0 or p_effective_start_date is null then raise exception 'A positive pet fee and start date are required.';end if;insert into monthly_pet_fees(owner_id,id,animal_id,lease_id,amount_cents,status,effective_start_date,approval_evidence_id,approved_at)values(p_owner_id,'monthly_pet_fee_'||gen_random_uuid()::text,a.id,a.lease_id,p_monthly_fee_cents,'active',p_effective_start_date,p_approval_evidence_id,now())on conflict(owner_id,animal_id)do update set amount_cents=excluded.amount_cents,status='active',effective_start_date=excluded.effective_start_date,approval_evidence_id=excluded.approval_evidence_id,approved_at=excluded.approved_at,updated_at=now()returning * into fee;end if;end if;return jsonb_build_object('animal_id',a.id,'decision',p_decision,'classification',p_classification,'pet_fee_id',fee.id);end$$;
grant execute on function review_rental_animal(text,text,text,text,text,bigint,date)to authenticated;

create or replace function prevent_assistance_animal_pet_fee()returns trigger language plpgsql security definer set search_path=public as $$declare classification text;begin select a.classification into classification from rental_animals a where a.owner_id=new.owner_id and a.id=new.animal_id;if classification<>'pet'then raise exception 'Monthly pet fees are prohibited for assistance-animal review records.';end if;return new;end$$;
drop trigger if exists prevent_assistance_animal_pet_fee_trigger on monthly_pet_fees;create trigger prevent_assistance_animal_pet_fee_trigger before insert or update on monthly_pet_fees for each row execute function prevent_assistance_animal_pet_fee();revoke all on function prevent_assistance_animal_pet_fee()from public,anon,authenticated;
